import type { AFEType } from "../../src/types/interfaces";

export const singleAFE: AFEType[] = [{
    id: '123e4567-e89b-12d3-a456-426614174000',
    operator: '123e4567-e89b-12d3-a456-426614174000',
    created_at: 'May 1',
    afe_type: 'Drilling',
    afe_number: 'TESTNum1',
    description: 'Desc',
    total_gross_estimate: 100,
    version_string: '',
    supp_gross_estimate: 0,
    operator_wi: 10,
    partnerID: '',
    partner_name: 'PartnerNaem',
    partner_wi: 23,
    partner_status: 'New',
    op_status: 'IAPP',
    iapp_date: 'May5',
    last_mod_date: 'Jun3',
    legacy_chainID: 1,
    legacy_afeid: 2,
    chain_version: 1,
    source_system_id: 'ex ID'
}];

export const twoAFErecords: AFEType[] = [
    {
        id: '123e4567-e89b-12d3-a456-426614174000',
        operator: 'Nav Oil',
        created_at: 'May 1',
        afe_type: 'Drilling',
        afe_number: 'TESTNum1',
        description: 'Desc',
        total_gross_estimate: 100,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 10,
        partnerID: '',
        partner_name: 'Athena Minerals Inc.',
        partner_wi: 23,
        partner_status: 'New',
        op_status: 'IAPP',
        iapp_date: 'May5',
        last_mod_date: 'Jun3',
        legacy_chainID: 1,
        legacy_afeid: 2,
        chain_version: 1,
        source_system_id: 'ex ID'
    },
    {
        id: '123e4567-e89b-12d3-a456-426614174001',
        operator: 'Navigator Corporation',
        created_at: 'May 1',
        afe_type: 'Drilling',
        afe_number: 'TESTNum1',
        description: 'Desc',
        total_gross_estimate: 100,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 10,
        partnerID: '',
        partner_name: 'Partner 2',
        partner_wi: 23,
        partner_status: 'New',
        op_status: 'IAPP',
        iapp_date: 'May5',
        last_mod_date: 'Jun3',
        legacy_chainID: 1,
        legacy_afeid: 2,
        chain_version: 1,
        source_system_id: 'ex ID'
    }];

    export const twoOperatedAFErecords: AFEType[] = [
        {
            id: '123e4567-e89b-12d3-a456-426614174000',
            operator: 'Navigator Corporation',
            created_at: 'May 1',
            afe_type: 'Drilling',
            afe_number: 'TESTNum1',
            description: 'Desc',
            total_gross_estimate: 100,
            version_string: '',
            supp_gross_estimate: 0,
            operator_wi: 10,
            partnerID: '',
            partner_name: 'Partner 1',
            partner_wi: 23,
            partner_status: 'New',
            op_status: 'IAPP',
            iapp_date: 'May5',
            last_mod_date: 'Jun3',
            legacy_chainID: 1,
            legacy_afeid: 2,
            chain_version: 1,
            source_system_id: 'ex ID'
        },
        {
            id: '123e4567-e89b-12d3-a456-426614174001',
            operator: 'Navigator Corporation',
            created_at: 'May 1',
            afe_type: 'Drilling',
            afe_number: 'TESTNum1',
            description: 'Desc',
            total_gross_estimate: 100,
            version_string: '',
            supp_gross_estimate: 0,
            operator_wi: 10,
            partnerID: '',
            partner_name: 'Partner 2',
            partner_wi: 23,
            partner_status: 'New',
            op_status: 'IAPP',
            iapp_date: 'May5',
            last_mod_date: 'Jun3',
            legacy_chainID: 1,
            legacy_afeid: 2,
            chain_version: 1,
            source_system_id: 'ex ID'
        }];
    
        export const twoNonOperatedAFErecords: AFEType[] = [
            {
                id: '123e4567-e89b-12d3-a456-426614174000',
                operator: 'Nav Oil',
                created_at: 'May 1',
                afe_type: 'Drilling',
                afe_number: 'TESTNum1',
                description: 'Desc',
                total_gross_estimate: 100,
                version_string: '',
                supp_gross_estimate: 0,
                operator_wi: 10,
                partnerID: '',
                partner_name: 'Athena Minerals Inc.',
                partner_wi: 23,
                partner_status: 'New',
                op_status: 'IAPP',
                iapp_date: 'May5',
                last_mod_date: 'Jun3',
                legacy_chainID: 1,
                legacy_afeid: 2,
                chain_version: 1,
                source_system_id: 'ex ID'
            },
            {
                id: '123e4567-e89b-12d3-a456-426614174001',
                operator: 'Nav Oil',
                created_at: 'May 1',
                afe_type: 'Drilling',
                afe_number: 'TESTNum1',
                description: 'Desc',
                total_gross_estimate: 100,
                version_string: '',
                supp_gross_estimate: 0,
                operator_wi: 10,
                partnerID: '',
                partner_name: 'Athena Minerals Inc.',
                partner_wi: 23,
                partner_status: 'New',
                op_status: 'IAPP',
                iapp_date: 'May5',
                last_mod_date: 'Jun3',
                legacy_chainID: 1,
                legacy_afeid: 2,
                chain_version: 1,
                source_system_id: 'ex ID'
            }];