import type { AFEType, EstimatesSupabaseType, OperatorOrPartnerList, UserProfileRecordSupabaseType } from "../../src/types/interfaces";

// Postgres timestamp format
const postgresTimestamp = '2026-01-15 10:30:00';
// Or with timezone
const postgresTimestampTZ = '2026-01-15 10:30:00+00';
const postgresDate = new Date(2026, 0, 25)

const testDateTimestamp = new Date(postgresTimestamp);
const testDateTimeStampTZ = new Date(postgresTimestampTZ);

const apc_op_id = '123e4567-e89b-12d3-a456-426614174000';
const apc_op_id2 = 'a4367e56-14bf-4bd1-b0f1-fecc7d97b58c';
const apc_part_id = '';

export const apc_op_id_Nav = 'a4367e56-14bf-4bd1-b0f1-fecc7d97b58c';
export const apc_op_id_CW = '3b34a78a-13ad-40b5-aecd-268d56dd5e0d';
export const apc_part_id_John = '8ed0a285-0011-4f56-962f-c46bc0889d1b';
export const apc_part_id_Athena = '626390b5-6f63-4caa-a0aa-b333a15eaf59';

const apc_afe_id1 = '025439e7-c970-44f0-9e50-f7b28f70199a';
const apc_afe_id2 = '34d7bd01-d43b-4e3a-a586-34f0297a8008';

const userID1 = '13e69340-d14c-45a9-96a8-142795925487'




export const singleAFE: AFEType[] = [{
    id: apc_afe_id1,
    operator: 'Gas & Oil Company',
    created_at: testDateTimeStampTZ,
    afe_type: 'Drilling',
    afe_number: 'AFE Test 1',
    description: 'Description AFE 1',
    total_gross_estimate: 1000,
    version_string: '',
    supp_gross_estimate: 0,
    operator_wi: 10,
    partnerID: '',
    partner_name: 'Partner Name AFE1',
    partner_wi: 23,
    partner_status: 'New',
    op_status: 'IAPP',
    iapp_date: 'Jan 5, 2026',
    last_mod_date: 'Jan 4, 2026',
    legacy_chainID: 427,
    legacy_afeid: 1,
    chain_version: 427,
    source_system_id: 'external source ID',
    sortID: 1,
    partner_status_date: postgresDate,
    apc_op_id: apc_op_id,
    archived: false,
    partner_archived: false,
    apc_partner_id: apc_part_id,
    well_name: 'Many'
}];

export const twoAFErecords: AFEType[] = [
    {
    id: apc_afe_id1,
    operator: 'Gas & Oil Company',
    created_at: testDateTimeStampTZ,
    afe_type: 'Drilling',
    afe_number: 'AFE Test 1',
    description: 'Description AFE 1',
    total_gross_estimate: 1000,
    version_string: '',
    supp_gross_estimate: 0,
    operator_wi: 10,
    partnerID: '',
    partner_name: 'Partner Name AFE1',
    partner_wi: 23,
    partner_status: 'New',
    op_status: 'IAPP',
    iapp_date: 'Jan 5, 2026',
    last_mod_date: 'Jan 4, 2026',
    legacy_chainID: 427,
    legacy_afeid: 1,
    chain_version: 427,
    source_system_id: 'external source ID',
    sortID: 1,
    partner_status_date: postgresDate,
    apc_op_id: apc_op_id,
    archived: false,
    partner_archived: false,
    apc_partner_id: apc_part_id,
    well_name: 'Many'
    },
    {
    id: apc_afe_id2,
    operator: 'Gas & Oil Company',
    created_at: testDateTimeStampTZ,
    afe_type: 'Drilling',
    afe_number: 'AFE Test 2',
    description: 'Description AFE 2',
    total_gross_estimate: 1000,
    version_string: 'S1',
    supp_gross_estimate: 0,
    operator_wi: 10,
    partnerID: '',
    partner_name: 'Partner Name AFE2',
    partner_wi: 23,
    partner_status: 'New',
    op_status: 'IAPP',
    iapp_date: 'Jan 5, 2026',
    last_mod_date: 'Jan 4, 2026',
    legacy_chainID: 428,
    legacy_afeid: 2,
    chain_version: 428,
    source_system_id: 'external source ID',
    sortID: 2,
    partner_status_date: postgresDate,
    apc_op_id: apc_op_id,
    archived: false,
    partner_archived: false,
    apc_partner_id: apc_part_id,
    well_name: 'Many'
    }];

export const twoOperatedAFErecords: AFEType[] = [
    {
        id: '123e4567-e89b-12d3-a456-426614174000',
        operator: 'Navigator Corporation',
        created_at: testDateTimeStampTZ,
        afe_type: 'Drilling',
        afe_number: 'Op Test 1',
        description: 'Op Test 1 Description',
        total_gross_estimate: 100,
        version_string: 'S1',
        supp_gross_estimate: 0,
        operator_wi: 10,
        partnerID: '',
        partner_name: 'Partner 1',
        partner_wi: 23,
        partner_status: 'Viewed',
        op_status: 'IAPP',
        iapp_date: 'May5',
        last_mod_date: 'Jun3',
        legacy_chainID: 1,
        legacy_afeid: 2,
        chain_version: 1,
        source_system_id: 'ex ID',
        sortID: 1,
        partner_status_date: postgresDate,
        apc_op_id: apc_op_id,
        archived: false,
        partner_archived: false,
        apc_partner_id: apc_part_id,
        well_name: 'Many'
    },
    {
        id: '123e4567-e89b-12d3-a456-426614174000',
        operator: 'Navigator Corporation',
        created_at: testDateTimeStampTZ,
        afe_type: 'Drilling',
        afe_number: 'Op Test 2',
        description: 'Op Test 2 Description',
        total_gross_estimate: 100,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 10,
        partnerID: '',
        partner_name: 'Partner 1',
        partner_wi: 23,
        partner_status: 'New',
        op_status: 'IAPP',
        iapp_date: 'May5',
        last_mod_date: 'Jun3',
        legacy_chainID: 12,
        legacy_afeid: 1,
        chain_version: 12,
        source_system_id: 'ex ID',
        sortID: 1,
        partner_status_date: postgresDate,
        apc_op_id: apc_op_id,
        archived: false,
        partner_archived: false,
        apc_partner_id: apc_part_id,
        well_name: 'Many'
    }];

export const twoNonOperatedAFErecords: AFEType[] = [
    {
        id: '123e4567-e89b-12d3-a456-426614174000',
        operator: 'Other Operator',
        created_at: testDateTimeStampTZ,
        afe_type: 'Drilling',
        afe_number: 'NonOp Test 1',
        description: 'NonOp Test 1 Description',
        total_gross_estimate: 100,
        version_string: 'S1',
        supp_gross_estimate: 0,
        operator_wi: 10,
        partnerID: '',
        partner_name: 'Op as Partner',
        partner_wi: 23,
        partner_status: 'New',
        op_status: 'IAPP',
        iapp_date: 'May5',
        last_mod_date: 'Jun3',
        legacy_chainID: 1,
        legacy_afeid: 2,
        chain_version: 1,
        source_system_id: 'ex ID',
        sortID: 1,
        partner_status_date: postgresDate,
        apc_op_id: apc_op_id,
        archived: false,
        partner_archived: false,
        apc_partner_id: apc_part_id,
        well_name: 'Many'
    },
    {
        id: '123e4567-e89b-12d3-a456-426614174000',
        operator: 'Other Operator',
        created_at: testDateTimeStampTZ,
        afe_type: 'Drilling',
        afe_number: 'NonOp Test 2',
        description: 'NonOp Test 2 Description',
        total_gross_estimate: 100,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 10,
        partnerID: '',
        partner_name: 'Partner 1',
        partner_wi: 23,
        partner_status: 'New',
        op_status: 'IAPP',
        iapp_date: 'May5',
        last_mod_date: 'Jun3',
        legacy_chainID: 13,
        legacy_afeid: 1,
        chain_version: 13,
        source_system_id: 'ex ID',
        sortID: 1,
        partner_status_date: postgresDate,
        apc_op_id: apc_op_id,
        archived: false,
        partner_archived: false,
        apc_partner_id: apc_part_id,
        well_name: 'Many'
    }];

export const singleEstimateRecord: EstimatesSupabaseType[] = [
    {
        id: 1,
        amount_gross: 100,
        partner_wi: 20.00,
        partner_net_amount: 20.00,
        operator_account_number: 'OP.ACCT.NUM',
        operator_account_description: 'Mock account desc',
        operator_account_group: '1. DRILLING',
        partner_account_number: 'P.ACCT.NUM',
        partner_account_description: 'P ACCT DESC',
        partner_account_group: 'P ACCT GROUP'
    },
    {
        id: 1,
        amount_gross: 100,
        partner_wi: 20.00,
        partner_net_amount: 20.00,
        operator_account_number: 'OP.ACCT.NUM',
        operator_account_description: 'Mock account desc',
        operator_account_group: '1. DRILLING',
        partner_account_number: 'P.ACCT.NUM',
        partner_account_description: 'P ACCT DESC',
        partner_account_group: 'P ACCT GROUP'
    }
];

export const parterNewStatus: AFEType = {
    id: '123e4567-e89b-12d3-a456-426614174000',
    operator: '123e4567-e89b-12d3-a456-426614174000',
    created_at: testDateTimeStampTZ,
    afe_type: 'Drilling',
    afe_number: 'TESTNum1',
    description: 'Desc',
    total_gross_estimate: 100,
    version_string: '',
    supp_gross_estimate: 0,
    operator_wi: 10,
    partnerID: '',
    partner_name: 'PartnerNaem',
    partner_wi: 23,
    partner_status: 'New',
    op_status: 'IAPP',
    iapp_date: 'May5',
    last_mod_date: 'Jun3',
    legacy_chainID: 1,
    legacy_afeid: 2,
    chain_version: 1,
    source_system_id: 'ex ID',
    sortID: 1,
    partner_status_date: new Date(),
    apc_op_id: apc_op_id,
    archived: false,
    partner_archived: false,
    apc_partner_id: apc_part_id,
    well_name: 'Many'
};

export const parterViewStatus: AFEType = {
    id: '123e4567-e89b-12d3-a456-426614174000',
    operator: '123e4567-e89b-12d3-a456-426614174000',
    created_at: new Date(),
    afe_type: 'Drilling',
    afe_number: 'TESTNum1',
    description: 'Desc',
    total_gross_estimate: 100,
    version_string: '',
    supp_gross_estimate: 0,
    operator_wi: 10,
    partnerID: '',
    partner_name: 'PartnerNaem',
    partner_wi: 23,
    partner_status: 'Viewed',
    op_status: 'IAPP',
    iapp_date: 'May5',
    last_mod_date: 'Jun3',
    legacy_chainID: 1,
    legacy_afeid: 2,
    chain_version: 1,
    source_system_id: 'ex ID',
    sortID: 1,
    partner_status_date: new Date(),
    apc_op_id: apc_op_id,
    archived: false,
    partner_archived: false,
    apc_partner_id: apc_part_id,
    well_name: 'Many'
};
export const parterApprovedStatus: AFEType = {
    id: '123e4567-e89b-12d3-a456-426614174000',
    operator: '123e4567-e89b-12d3-a456-426614174000',
    created_at: testDateTimeStampTZ,
    afe_type: 'Drilling',
    afe_number: 'TESTNum1',
    description: 'Desc',
    total_gross_estimate: 100,
    version_string: '',
    supp_gross_estimate: 0,
    operator_wi: 10,
    partnerID: '',
    partner_name: 'PartnerNaem',
    partner_wi: 23,
    partner_status: 'Approved',
    op_status: 'IAPP',
    iapp_date: 'May5',
    last_mod_date: 'Jun3',
    legacy_chainID: 1,
    legacy_afeid: 2,
    chain_version: 1,
    source_system_id: 'ex ID',
    sortID: 1,
    partner_status_date: new Date(),
    apc_op_id: apc_op_id,
    archived: false,
    partner_archived: false,
    apc_partner_id: apc_part_id,
    well_name: 'Many'
};
export const parterRejectedStatus: AFEType = {
    id: '123e4567-e89b-12d3-a456-426614174000',
    operator: '123e4567-e89b-12d3-a456-426614174000',
    created_at: testDateTimeStampTZ,
    afe_type: 'Drilling',
    afe_number: 'TESTNum1',
    description: 'Desc',
    total_gross_estimate: 100,
    version_string: '',
    supp_gross_estimate: 0,
    operator_wi: 10,
    partnerID: '',
    partner_name: 'PartnerNaem',
    partner_wi: 23,
    partner_status: 'Rejected',
    op_status: 'IAPP',
    iapp_date: 'May5',
    last_mod_date: 'Jun3',
    legacy_chainID: 1,
    legacy_afeid: 2,
    chain_version: 1,
    source_system_id: 'ex ID',
    sortID: 1,
    partner_status_date: new Date(),
    apc_op_id: apc_op_id,
    archived: false,
    partner_archived: false,
    apc_partner_id: apc_part_id,
    well_name: 'Many'
};

export const loggedInUser: UserProfileRecordSupabaseType = {
    firstName: 'User 1',
    lastName: 'Athena',
    email: 'user@email',
    active: true,
    is_super_user: false,
    operatorRoles: [
        {
        apc_name: 'Corr and Whit Oils',
        apc_address: {
            address_active: true,
            id: 66,
            street: '1234 Main',
            suite:'',
            city: 'Houston',
            state: 'Texas',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: true,
        is_partner_permission: false,
        id: 120,
        role: 2,
        active: true,
        apc_id: apc_op_id,
        apc_address_id: 66
    },
    {
        apc_name: 'Corr and Whit Oils',
        apc_address: {
            address_active: true,
            id: 66,
            street: '1234 Main',
            suite:'',
            city: 'Houston',
            state: 'Texas',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: true,
        is_partner_permission: false,
        id: 121,
        role: 4,
        active: true,
        apc_id: apc_op_id,
        apc_address_id: 66
    },
    {
        apc_name: 'Corr and Whit Oils',
        apc_address: {
            address_active: true,
            id: 66,
            street: '1234 Main',
            suite:'',
            city: 'Houston',
            state: 'Texas',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: true,
        is_partner_permission: false,
        id: 122,
        role: 8,
        active: true,
        apc_id: apc_op_id,
        apc_address_id: 66
    }
    ],
    partnerRoles: [
        {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 35,
        role: 3,
        active: true,
        apc_id: '8ed0a285-0011-4f56-962f-c46bc0889d1b',
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 72,
        role: 9,
        active: true,
        apc_id: '8ed0a285-0011-4f56-962f-c46bc0889d1b',
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 74,
        role: 5,
        active: true,
        apc_id: '8ed0a285-0011-4f56-962f-c46bc0889d1b',
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 185,
        role: 6,
        active: true,
        apc_id: '8ed0a285-0011-4f56-962f-c46bc0889d1b',
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 7,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 186,
        role: 3,
        active: true,
        apc_id: '8ed0a285-0011-4f56-962f-c46bc0889d1b',
        apc_address_id: 7
    }
    
    ],
};

//User has no view rights to Operated and Non Op view rights to Athena can approve
export const loggedInUserNoOpViewRightsAthena: UserProfileRecordSupabaseType = {
    firstName: 'Jane',
    lastName: 'Athena',
    email: 'user@email',
    active: true,
    is_super_user: false,
    operatorRoles: [],
    partnerRoles: [
        {
        apc_name: 'Athena Minerals',
        apc_address: {
            address_active: true,
            id: 7,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 35,
        role: 3,
        active: true,
        apc_id: apc_part_id_Athena,
        apc_address_id: 7
    },
    {
        apc_name: 'Athena Minerals',
        apc_address: {
            address_active: true,
            id: 7,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 72,
        role: 9,
        active: true,
        apc_id: apc_part_id_Athena,
        apc_address_id: 7
    },
    {
        apc_name: 'Athena Minerals',
        apc_address: {
            address_active: true,
            id: 7,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 74,
        role: 5,
        active: true,
        apc_id: apc_part_id_Athena,
        apc_address_id: 7
    },
    {
        apc_name: 'Athena Minerals',
        apc_address: {
            address_active: true,
            id: 7,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 185,
        role: 6,
        active: true,
        apc_id: apc_part_id_Athena,
        apc_address_id: 7
    }
    
    ],
};

//User has view rights to operated AFEs for Nav Oils and Non Op view rights to John Ross and can Approve NonOp AFEs
export const loggedInUserOpNavOilsPartnerJohnRoss: UserProfileRecordSupabaseType = {
    firstName: 'Tim',
    lastName: 'Ross',
    email: 'user@email',
    active: true,
    is_super_user: false,
    operatorRoles: [
        {
        apc_name: 'Nav Oils',
        apc_address: {
            address_active: true,
            id: 51,
            street: '1234 Main',
            suite:'',
            city: 'Houston',
            state: 'Texas',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: true,
        is_partner_permission: false,
        id: 46,
        role: 2,
        active: true,
        apc_id: apc_op_id_Nav,
        apc_address_id: 51
    },
    {
        apc_name: 'Nav Oils',
        apc_address: {
            address_active: true,
            id: 51,
            street: '1234 Main',
            suite:'',
            city: 'Houston',
            state: 'Texas',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: true,
        is_partner_permission: false,
        id: 49,
        role: 4,
        active: true,
        apc_id: apc_op_id_Nav,
        apc_address_id: 51
    },
    {
        apc_name: 'Nav Oils',
        apc_address: {
            address_active: true,
            id: 51,
            street: '1234 Main',
            suite:'',
            city: 'Houston',
            state: 'Texas',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: true,
        is_partner_permission: false,
        id: 52,
        role: 8,
        active: true,
        apc_id: apc_op_id_Nav,
        apc_address_id: 51
    }
    ],
    partnerRoles: [
        {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 35,
        role: 3,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 72,
        role: 9,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 74,
        role: 5,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 185,
        role: 6,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    }
    
    ],
};

export const loggedInUserIsSuperUser: UserProfileRecordSupabaseType = {
    firstName: 'Tim',
    lastName: 'Ross',
    email: 'user@email',
    active: true,
    is_super_user: true,
    operatorRoles: [],
    partnerRoles: [],
};

export const AFEsFromSupbase: AFEType[] = [
    //Operated by Nav Oil & John Ross Partner NOT ARCHIVED
    {
        id: "025439e7-c970-44f0-9e50-f7b28f70199a",
        created_at:  new Date("2025-10-22 17:10:50.830331+00"),
        afe_type: "DRILLING",
        afe_number: "26D001",
        description: "Drill SHIELDS-CANTRELL #1",
        total_gross_estimate: 563603.25,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 25,
        partner_name: "John Ross Exploration Inc",
        partner_wi: 50,
        partner_status: "Approved",
        op_status: "IAPP",
        iapp_date: "2025-10-08",
        last_mod_date: "2025-10-08",
        legacy_chainID: 427,
        legacy_afeid: 427,
        chain_version: 1,
        source_system_id: "8c7a4be7-e577-499d-8c7b-266a1549a020",
        apc_partner_id: "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        partnerID: "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        partner_status_date: new Date("2025-12-17 19:42:56.678+00"),
        sortID: 156,
        archived: false,
        partner_archived: false,
        apc_op_id: "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
        operator: 'Navigator Oil',
        well_name: "SHIELDS-CANTRELL #1",
    },
    //Operated by Corr Whit Oil & John Ross Partner NOT ARCHIVED
    {
        id: "34d7bd01-d43b-4e3a-a586-34f0297a8008",
        created_at:  new Date("2025-10-22 17:10:47.867426+00"),
        afe_type: "DRILLING",
        afe_number: "25D001",
        description: "Drill SHIELDS-CANTRELL #1",
        total_gross_estimate: 563603.25,
        version_string: "S2",
        supp_gross_estimate: 2333.1,
        operator_wi: 65,
        partner_name: "John Ross Exploration Inc",
        partner_wi: 20,
        partner_status: "New",
        op_status: "IAPP",
        iapp_date: "2025-08-12",
        last_mod_date: "2025-10-08",
        legacy_chainID: 414,
        legacy_afeid: 425,
        chain_version: 3,
        source_system_id: "e217aede-6af1-4696-8776-4d56d1ac16bf",
        apc_partner_id: "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        partnerID: "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        partner_status_date: new Date(),
        sortID: 153,
        archived: false,
        partner_archived: false,
        apc_op_id: "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        operator: 'Corr and Whit Oil',
        well_name: "Many"
    },
    //Operated by Nav Oil & John Ross Partner NOT ARCHIVED
    {
        id: "4b6cebbf-ca88-4e9e-8479-dd50cc13e03d",
        created_at:  new Date("2025-11-15 00:00:06.292558+00"),
        afe_type: "DRILLING",
        afe_number: "06D111",
        description: "Drill DRAKE SURVEY-MASON #1",
        total_gross_estimate: 275000,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 80,
        partner_name: "John Ross Exploration Inc",
        partner_wi: 20,
        partner_status: "Viewed",
        op_status: "FAPP",
        iapp_date: "2025-11-14",
        last_mod_date: "2025-11-14",
        legacy_chainID: 176,
        legacy_afeid: 176,
        chain_version: 1,
        source_system_id: "ba0c1c4f-81e5-4509-8089-6c9bc4919264",
        apc_partner_id: "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        partnerID: "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        partner_status_date: new Date(),
        sortID: 166,
        archived: false,
        partner_archived: false,
        apc_op_id: "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
        operator: 'Navigator Oil',
        well_name: "DRAKE SURVEY-MASON #1"
    },
    //Operated by Corr Whit Oil & John Ross Partner NOT ARCHIVED
    {
        id: "88760c34-38b0-4bdd-a6d1-59376ec8c9be",
        created_at:  new Date("2025-11-15 00:00:03.139299+00"),
        afe_type: "DRILLING",
        afe_number: "06D111",
        description: "Drill DRAKE SURVEY-MASON #1",
        total_gross_estimate: 275000,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 80,
        partner_name: "John Ross Exploration Inc",
        partner_wi: 20,
        partner_status: "New",
        op_status: "FAPP",
        iapp_date: "2025-11-14",
        last_mod_date: "2025-11-14",
        legacy_chainID: 176,
        legacy_afeid: 176,
        chain_version: 1,
        source_system_id: "ba0c1c4f-81e5-4509-8089-6c9bc4919264",
        apc_partner_id: "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        partnerID: "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        partner_status_date: new Date("2025-12-17 18:45:49.184+00"),
        sortID: 165,
        archived: false,
        partner_archived: false,
        apc_op_id: "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        operator: 'Corr and Whit Oil',
        well_name: "DRAKE SURVEY-MASON #1"
    },
    //Operated by Corr Whit Oil & John Ross Partner NOT ARCHIVED
    {
        id: "9f1ab2b4-3f58-4d6e-8365-f5126c4d0b4c",
        created_at:  new Date("2025-10-22 17:10:47.867426+00"),
        afe_type: "DRILLING",
        afe_number: "26D001",
        description: "Drill SHIELDS-CANTRELL #1",
        total_gross_estimate: 563603.25,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 25,
        partner_name: "John Ross Exploration Inc",
        partner_wi: 50,
        partner_status: "New",
        op_status: "IAPP",
        iapp_date: "2025-10-08",
        last_mod_date: "2025-10-08",
        legacy_chainID: 427,
        legacy_afeid: 427,
        chain_version: 1,
        source_system_id: "8c7a4be7-e577-499d-8c7b-266a1549a020",
        apc_partner_id: "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        partnerID: "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        partner_status_date: new Date(),
        sortID: 154,
        archived: false,
        partner_archived: false,
        apc_op_id: "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        operator: 'Corr and Whit Oil',
        well_name: "SHIELDS-CANTRELL #1"
    },
    //Operated by Nav Oil & Athena Partner NOT ARCHIVED
    {
        id: "9f6dce03-0eea-484a-bcae-0b4659640daa",
        created_at:  new Date("2025-10-22 17:10:50.830331+00"),
        afe_type: "DRILLING",
        afe_number: "25D001",
        description: "Drill SHIELDS-CANTRELL #1",
        total_gross_estimate: 563603.25,
        version_string: "S2",
        supp_gross_estimate: 2333.1,
        operator_wi: 65,
        partner_name: "Athena Minerals Inc.",
        partner_wi: 15,
        partner_status: "Viewed",
        op_status: "IAPP",
        iapp_date: "2025-08-12",
        last_mod_date: "2025-10-08",
        legacy_chainID: 414,
        legacy_afeid: 425,
        chain_version: 3,
        source_system_id: "e217aede-6af1-4696-8776-4d56d1ac16bf",
        apc_partner_id: "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        partnerID: "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        partner_status_date: new Date(),
        sortID: 157,
        archived: false,
        partner_archived: false,
        apc_op_id: "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
        operator: 'Navigator Oil',
        well_name: "Many"
    },
    //Operated by Nav Oil & Athena Partner NOT ARCHIVED
    {
        id: "d9238faa-2914-4215-8ca2-78384663102d",
        created_at:  new Date("2025-10-22 17:10:50.830331+00"),
        afe_type: "DRILLING",
        afe_number: "26D001",
        description: "Drill SHIELDS-CANTRELL #1",
        total_gross_estimate: 563603.25,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 25,
        partner_name: "Athena Minerals Inc.",
        partner_wi: 25,
        partner_status: "Approved",
        op_status: "IAPP",
        iapp_date: "2025-10-08",
        last_mod_date: "2025-10-08",
        legacy_chainID: 427,
        legacy_afeid: 427,
        chain_version: 1,
        source_system_id: "8c7a4be7-e577-499d-8c7b-266a1549a020",
        apc_partner_id: "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        partnerID: "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        partner_status_date: new Date("2025-12-12 21:55:38.237+00"),
        sortID: 158,
        archived: false,
        partner_archived: false,
        apc_op_id: "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
        operator: 'Navigator Oil',
        well_name: "SHIELDS-CANTRELL #1"
    },
    //Operated by Nav Oil & John Ross Partner NOT ARCHIVED
    {
        id: "e5676564-f4f2-40ec-b115-52635ec0593b",
        created_at:  new Date("2025-10-22 17:10:50.830331+00"),
        afe_type: "DRILLING",
        afe_number: "25D001",
        description: "Drill SHIELDS-CANTRELL #1",
        total_gross_estimate: 563603.25,
        version_string: "S2",
        supp_gross_estimate: 2333.1,
        operator_wi: 65,
        partner_name: "John Ross Exploration Inc",
        partner_wi: 20,
        partner_status: "Approved",
        op_status: "IAPP",
        iapp_date: "2025-08-12",
        last_mod_date: "2025-10-08",
        legacy_chainID: 414,
        legacy_afeid: 425,
        chain_version: 3,
        source_system_id: "e217aede-6af1-4696-8776-4d56d1ac16bf",
        apc_partner_id: "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        partnerID: "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        partner_status_date: new Date("2026-01-19 01:26:45.053+00"),
        sortID: 155,
        archived: false,
        partner_archived: false,
        apc_op_id: "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
        operator: 'Navigator Oil',
        well_name: "Many"
    },
    //Operated by Corr Whit Oil & Athena Partner NOT ARCHIVED
    {
        id: "e74130a2-d985-4179-b0ff-9cc7e077d77e",
        created_at:  new Date("2025-10-22 17:10:47.867426+00"),
        afe_type: "DRILLING",
        afe_number: "25D001",
        description: "Drill SHIELDS-CANTRELL #1",
        total_gross_estimate: 563603.25,
        version_string: "S2",
        supp_gross_estimate: 2333.1,
        operator_wi: 65,
        partner_name: "Athena Minerals Inc.",
        partner_wi: 15,
        partner_status: "Viewed",
        op_status: "IAPP",
        iapp_date: "2025-08-12",
        last_mod_date: "2025-10-08",
        legacy_chainID: 414,
        legacy_afeid: 425,
        chain_version: 3,
        source_system_id: "e217aede-6af1-4696-8776-4d56d1ac16bf",
        apc_partner_id: "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        partnerID: "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        partner_status_date: new Date(),
        sortID: 151,
        archived: false,
        partner_archived: false,
        apc_op_id: "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        operator: 'Corr and Whit Oil',
        well_name: "Many"
    },
    //Operated by Nav Oil & Athena Partner NOT ARCHIVED
    {
        id: "f7247f99-2094-45b7-acb8-6bbd7070e261",
        created_at: new Date("2025-10-22 17:10:47.867426+00"),
        afe_type: "DRILLING",
        afe_number: "26D001",
        description: "Drill SHIELDS-CANTRELL #1",
        total_gross_estimate: 563603.25,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 25,
        partner_name: "Athena Minerals Inc.",
        partner_wi: 25,
        partner_status: "Viewed",
        op_status: "IAPP",
        iapp_date: "2025-10-08",
        last_mod_date: "2025-10-08",
        legacy_chainID: 427,
        legacy_afeid: 427,
        chain_version: 1,
        source_system_id: "8c7a4be7-e577-499d-8c7b-266a1549a020",
        apc_partner_id: "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        partnerID: "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        partner_status_date: new Date(),
        sortID: 152,
        archived: false,
        partner_archived: false,
        apc_op_id: "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        operator: 'Corr and Whit Oil',
        well_name: "SHIELDS-CANTRELL #1"
    }
];

export const OperatorDropDown: OperatorOrPartnerList[] = [
    {
        apc_id: "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        apc_name: "Corr and Whit Oils",
        apc_address: {
            street: "6789 S Blvd",
            suite: "",
            city: "Houston",
            state: "Texas",
            zip: "90078",
            country: "United States",
            address_active: true,
            id: 66
        }
    },
    {
        apc_id: "da4bac27-30eb-40cf-9b33-ba93e3c3b3b5",
        apc_name: "Corr Mike oil",
        apc_address: {
            street: "123213",
            suite: "",
            city: "Houston",
            state: "Texas",
            zip: "90021",
            country: "United States",
            address_active: false,
            id: 67
        }
    },
    {
        apc_id: "e769175a-5d6c-48b7-a639-489f4a39e647",
        apc_name: "Corr Oil",
        apc_address: {
            street: "1234 Main",
            suite: "",
            city: "Austin",
            state: "Texas",
            zip: "90087",
            country: "United States",
            address_active: true,
            id: 52
        }
    },
    {
        apc_id: "1bcad1a0-9419-49da-999e-f7bf95339e90",
        apc_name: "Denver Oil",
        apc_address: {
            street: "5454 Broad Street",
            suite: "",
            city: "Denver",
            state: "CO",
            zip: "80202",
            country: "United States",
            address_active: true,
            id: 54
        }
    },
    {
        apc_id: "d0bc769a-b709-4d58-b563-acdf1d99c5a2",
        apc_name: "Denver Oil 2",
        apc_address: {
            street: "5434",
            suite: "",
            city: "Denv",
            state: "CO",
            zip: "90909",
            country: "United States",
            address_active: true,
            id: 55
        }
    },
    {
        apc_id: "f3f7d47d-bd77-41c7-8647-cb4b3761279c",
        apc_name: "Fortnite Oil",
        apc_address: {
            street: "98987",
            suite: "678",
            city: "Houston",
            state: "Texas",
            zip: "00988",
            country: "United States",
            address_active: true,
            id: 60
        }
    },
    {
        apc_id: "1beb7989-c65e-4c71-b68c-1a01b5e5850b",
        apc_name: "McKenzie Oil",
        apc_address: {
            street: "7898 Lousiana Blvd",
            suite: "",
            city: "Houston",
            state: "Texas",
            zip: "90087",
            country: "United States",
            address_active: true,
            id: 70
        }
    },
    {
        apc_id: "108ab43c-c1d6-4e6d-9305-c7ac3a622cc7",
        apc_name: "Mtn Bike Oil",
        apc_address: {
            street: "1234 Main Ave",
            suite: "",
            city: "Houston",
            state: "Texas",
            zip: "70020",
            country: "United States",
            address_active: true,
            id: 53
        }
    },
    {
        apc_id: "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
        apc_name: "Navigator Corporation",
        apc_address: {
            street: "897 South Street",
            suite: "",
            city: "Dallas",
            state: "Texas",
            zip: "98987",
            country: "United States",
            address_active: true,
            id: 51
        }
    },
    {
        apc_id: "1c738a5b-1fd1-4eb1-8710-fb87cadac4d1",
        apc_name: "Raiders Operator Energy Co",
        apc_address: {
            street: "6768 S Marion Street",
            suite: "3232",
            city: "Dallas",
            state: "Texas",
            zip: "00987",
            country: "United States",
            address_active: true,
            id: 65
        }
    },
    {
        apc_id: "8093e89f-85f1-4e24-ab91-a9df11e092f6",
        apc_name: "Third Wheel Oil and Gas",
        apc_address: {
            street: "8787 S Ogden",
            suite: "3232",
            city: "Dallas",
            state: "Texas",
            zip: "90078",
            country: "United States",
            address_active: true,
            id: 68
        }
    },
    {
        apc_id: "4482e4ea-29ad-4f57-a30a-d67a6b3d8ec1",
        apc_name: "This Third Wheel Oil and Gas",
        apc_address: {
            street: "6546 Logan Av",
            suite: "9999",
            city: "Midland",
            state: "Texas",
            zip: "09879",
            country: "United States",
            address_active: false,
            id: 69
        }
    },
    {
        apc_id: "a45536f3-ac27-4f3b-9a70-b0bb536d9fc6",
        apc_name: "Thorton Oil and Company",
        apc_address: {
            street: "3456 LandMine Way",
            suite: "67787",
            city: "Dallas",
            state: "Texas",
            zip: "77789",
            country: "United States",
            address_active: true,
            id: 72
        }
    },
    {
        apc_id: "01b272f7-ea18-48bc-9443-ba2f0c9376ff",
        apc_name: "Whit and Corr Oil",
        apc_address: {
            street: "1234 Snake Street",
            suite: "",
            city: "Fortnite Land",
            state: "CO",
            zip: "90900",
            country: "United States",
            address_active: true,
            id: 50
        }
    },
    {
        apc_id: "509165a9-532d-41ee-a2d5-c35c6c2124f3",
        apc_name: "Whitaker's Oil Company",
        apc_address: {
            street: "343456 La Ave",
            suite: "",
            city: "Dnver",
            state: "Colorado",
            zip: "90087",
            country: "United States",
            address_active: true,
            id: 71
        }
    }
];

export const PartnerDropdown: OperatorOrPartnerList[] = [
    {
        apc_id: "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        apc_name: "Athena Minerals Inc.",
        apc_address: null
    },
    {
        apc_id: "d09da985-e6be-48cd-8f52-c639353792c2",
        apc_name: "Corr and Whit Oil",
        apc_address: null
    },
    {
        apc_id: "dcfb31dd-1f04-45b0-8b70-5512c1fd4b24",
        apc_name: "Corr and Whit Oil",
        apc_address: null
    },
    {
        apc_id: "996917a3-415a-4e9d-a7a9-c04c6050fd3f",
        apc_name: "Corr and Whit Oil Partner",
        apc_address: null
    },
    {
        apc_id: "9e96df60-9fa3-4330-8318-972504f1af66",
        apc_name: "Corr and white",
        apc_address: null
    },
    {
        apc_id: "77cea5bb-5adf-40d6-a945-9aef30dd3b69",
        apc_name: "Denver 3",
        apc_address: null
    },
    {
        apc_id: "03559b6a-a1c5-43b3-8623-78d9acf2697a",
        apc_name: "Denver Oil 2",
        apc_address: null
    },
    {
        apc_id: "3d721e36-a900-4506-a120-2be2793bb163",
        apc_name: "Denver Oil 2",
        apc_address: null
    },
    {
        apc_id: "55817490-5603-4a65-9223-24c1f078dd81",
        apc_name: "Energy Oil Company",
        apc_address: null
    },
    {
        apc_id: "2606ec4f-7849-41bc-8b3d-85d96f1c6948",
        apc_name: "Fortnite Oil",
        apc_address: null
    },
    {
        apc_id: "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        apc_name: "John Ross Exploration Inc",
        apc_address: null
    },
    {
        apc_id: "db863d3c-606e-4fa6-b044-812d1f3cf6eb",
        apc_name: "Last Company",
        apc_address: null
    },
    {
        apc_id: "4045d710-476a-4ee0-b97b-be64933133ba",
        apc_name: "McKenzie Oil",
        apc_address: null
    },
    {
        apc_id: "e21bc803-be42-47d5-ab2d-6fe85ed15659",
        apc_name: "McKenzie Oil Energy",
        apc_address: null
    },
    {
        apc_id: "c99bacdd-8ee2-40b2-bbf2-2830a0b314d1",
        apc_name: "Third Wheel Energy Co.",
        apc_address: null
    },
    {
        apc_id: "a6606212-9c6a-44b2-9a8c-a04e48ea6f1f",
        apc_name: "Third Wheel Oil and Gas",
        apc_address: null
    },
    {
        apc_id: "74d7066b-d046-452d-8e04-ae3059e38dec",
        apc_name: "Thorton Oil and Company",
        apc_address: null
    },
    {
        apc_id: "3ab29a40-8ef0-4778-95fd-6c427b56496a",
        apc_name: "Whit and Corr Oil",
        apc_address: null
    }
];

export const afeReturnFromSupabase = [
    //Operated by Nav Oil & Athena is Partner NOT ARCHIVED 
    {
        "id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03W",
        "created_at": "2025-11-15T00:00:06.292558+00:00",
        "afe_type": "DRILLING",
        "afe_number": "DR26NAVAT",
        "description": "Drill DRAKE SURVEY-MASON #1",
        "total_gross_estimate": 275000,
        "version_string": null,
        "supp_gross_estimate": 0,
        "operator_wi": 80,
        "apc_partner_name": "Athena Minerals",
        "partner_wi": 20,
        "partner_status": "Viewed",
        "op_status": "FAPP",
        "iapp_date": "2025-11-14",
        "last_mod_date": "2025-11-14",
        "legacy_chainID": 176,
        "legacy_afeid": 176,
        "chain_version": 1,
        "source_system_id": "ba0c1c4f-81e5-4509-8089-6c9bc4919264",
        "apc_partner_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        "apc_operator_id": null,
        "partner_status_date": null,
        "sortID": 166,
        "archived": false,
        "partner_archived": false,
        "source_partner_id": null,
        "doc_fetch_status": "done",
        "doc_fetch_attempts": 2,
        "doc_last_fetch_at": "2025-12-30T20:09:51.423+00:00",
        "doc_last_error": null,
        "source_system_partner_id": "603ea163-a6b2-4f32-a8c5-67678401bf54",
        "apc_op_id": {
            "id": "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
            "name": "Navigator Corporation"
        },
        "well_name": "DRAKE SURVEY-MASON #1"
    },
    //Operated by Nav Oil & Athena is Partner OP Archived Partner NOT Archived 
    {
        "id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03E",
        "created_at": "2025-11-15T00:00:06.292558+00:00",
        "afe_type": "DRILLING",
        "afe_number": "AO06D111NA",
        "description": "Drill DRAKE SURVEY-MASON #1",
        "total_gross_estimate": 275000,
        "version_string": null,
        "supp_gross_estimate": 0,
        "operator_wi": 80,
        "apc_partner_name": "Athena Minerals",
        "partner_wi": 20,
        "partner_status": "Viewed",
        "op_status": "FAPP",
        "iapp_date": "2025-11-14",
        "last_mod_date": "2025-11-14",
        "legacy_chainID": 176,
        "legacy_afeid": 176,
        "chain_version": 1,
        "source_system_id": "ba0c1c4f-81e5-4509-8089-6c9bc4919264",
        "apc_partner_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        "apc_operator_id": null,
        "partner_status_date": null,
        "sortID": 166,
        "archived": true,
        "partner_archived": false,
        "source_partner_id": null,
        "doc_fetch_status": "done",
        "doc_fetch_attempts": 2,
        "doc_last_fetch_at": "2025-12-30T20:09:51.423+00:00",
        "doc_last_error": null,
        "source_system_partner_id": "603ea163-a6b2-4f32-a8c5-67678401bf54",
        "apc_op_id": {
            "id": "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
            "name": "Navigator Corporation"
        },
        "well_name": "DRAKE SURVEY-MASON #1"
    },
    //Operated by Nav Oil & Athena is Partner OP NOT Archived Partner IS Archived 
    {
        "id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03Q",
        "created_at": "2025-11-15T00:00:06.292558+00:00",
        "afe_type": "DRILLING",
        "afe_number": "PA07D111NA",
        "description": "Drill DRAKE SURVEY-MASON #1",
        "total_gross_estimate": 275000,
        "version_string": null,
        "supp_gross_estimate": 0,
        "operator_wi": 80,
        "apc_partner_name": "Athena Minerals",
        "partner_wi": 20,
        "partner_status": "Viewed",
        "op_status": "FAPP",
        "iapp_date": "2025-11-14",
        "last_mod_date": "2025-11-14",
        "legacy_chainID": 176,
        "legacy_afeid": 176,
        "chain_version": 1,
        "source_system_id": "ba0c1c4f-81e5-4509-8089-6c9bc4919264",
        "apc_partner_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        "apc_operator_id": null,
        "partner_status_date": null,
        "sortID": 166,
        "archived": false,
        "partner_archived": true,
        "source_partner_id": null,
        "doc_fetch_status": "done",
        "doc_fetch_attempts": 2,
        "doc_last_fetch_at": "2025-12-30T20:09:51.423+00:00",
        "doc_last_error": null,
        "source_system_partner_id": "603ea163-a6b2-4f32-a8c5-67678401bf54",
        "apc_op_id": {
            "id": "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
            "name": "Navigator Corporation"
        },
        "well_name": "DRAKE SURVEY-MASON #1"
    },
    //Operated by Corr Whit & John Ross is Partner NOT ARCHIVED 
    {
        "id": "88760c34-38b0-4bdd-a6d1-59376ec8c9be",
        "created_at": "2025-11-15T00:00:03.139299+00:00",
        "afe_type": "DRILLING",
        "afe_number": "06D111CJ",
        "description": "Drill DRAKE SURVEY-MASON #1",
        "total_gross_estimate": 275000,
        "version_string": null,
        "supp_gross_estimate": 0,
        "operator_wi": 80,
        "apc_partner_name": "John Ross Exploration Inc",
        "partner_wi": 20,
        "partner_status": "Approved",
        "op_status": "FAPP",
        "iapp_date": "2025-11-14",
        "last_mod_date": "2025-11-14",
        "legacy_chainID": 176,
        "legacy_afeid": 176,
        "chain_version": 1,
        "source_system_id": "ba0c1c4f-81e5-4509-8089-6c9bc4919264",
        "apc_partner_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_operator_id": null,
        "partner_status_date": "2025-12-17T18:45:49.184+00:00",
        "sortID": 165,
        "archived": false,
        "partner_archived": false,
        "source_partner_id": null,
        "doc_fetch_status": "done",
        "doc_fetch_attempts": 2,
        "doc_last_fetch_at": "2025-12-30T20:09:48.995+00:00",
        "doc_last_error": null,
        "source_system_partner_id": "603ea163-a6b2-4f32-a8c5-67678401bf54",
        "apc_op_id": {
            "id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
            "name": "Corr and Whit Oils"
        },
        "well_name": "DRAKE SURVEY-MASON #1"
    },
    //Operated by Corr Whit & Athena is Partner NOT ARCHIVED 
    {
        "id": "e74130a2-d985-4179-b0ff-9cc7e077d77e",
        "created_at": "2025-10-22T17:10:47.867426+00:00",
        "afe_type": "DRILLING",
        "afe_number": "25D001CA",
        "description": "Drill SHIELDS-CANTRELL #1",
        "total_gross_estimate": 563603.25,
        "version_string": "S2",
        "supp_gross_estimate": 2333.1,
        "operator_wi": 65,
        "apc_partner_name": "Athena Minerals Inc.",
        "partner_wi": 15,
        "partner_status": "Viewed",
        "op_status": "IAPP",
        "iapp_date": "2025-08-12",
        "last_mod_date": "2025-10-08",
        "legacy_chainID": 414,
        "legacy_afeid": 425,
        "chain_version": 3,
        "source_system_id": "e217aede-6af1-4696-8776-4d56d1ac16bf",
        "apc_partner_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        "apc_operator_id": null,
        "partner_status_date": null,
        "sortID": 151,
        "archived": false,
        "partner_archived": false,
        "source_partner_id": null,
        "doc_fetch_status": "pending",
        "doc_fetch_attempts": 0,
        "doc_last_fetch_at": null,
        "doc_last_error": null,
        "source_system_partner_id": "475e4d12-8a0b-4264-933d-d960936852b2",
        "apc_op_id": {
            "id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
            "name": "Corr and Whit Oils"
        },
        "well_name": "Many"
    },
    //Operated by Corr Whit & Athena is Partner NOT ARCHIVED 
    {
        "id": "f7247f99-2094-45b7-acb8-6bbd7070e261",
        "created_at": "2025-10-22T17:10:47.867426+00:00",
        "afe_type": "DRILLING",
        "afe_number": "26D001CA",
        "description": "Drill SHIELDS-CANTRELL #1",
        "total_gross_estimate": 563603.25,
        "version_string": null,
        "supp_gross_estimate": 0,
        "operator_wi": 25,
        "apc_partner_name": "Athena Minerals Inc.",
        "partner_wi": 25,
        "partner_status": "Viewed",
        "op_status": "IAPP",
        "iapp_date": "2025-10-08",
        "last_mod_date": "2025-10-08",
        "legacy_chainID": 427,
        "legacy_afeid": 427,
        "chain_version": 1,
        "source_system_id": "8c7a4be7-e577-499d-8c7b-266a1549a020",
        "apc_partner_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        "apc_operator_id": null,
        "partner_status_date": null,
        "sortID": 152,
        "archived": false,
        "partner_archived": false,
        "source_partner_id": null,
        "doc_fetch_status": "pending",
        "doc_fetch_attempts": 0,
        "doc_last_fetch_at": null,
        "doc_last_error": null,
        "source_system_partner_id": "475e4d12-8a0b-4264-933d-d960936852b2",
        "apc_op_id": {
            "id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
            "name": "Corr and Whit Oils"
        },
        "well_name": "SHIELDS-CANTRELL #1"
    },
    //Operated by Corr Whit & John Ross is Partner NOT ARCHIVED 
    {
        "id": "34d7bd01-d43b-4e3a-a586-34f0297a8008",
        "created_at": "2025-10-22T17:10:47.867426+00:00",
        "afe_type": "DRILLING",
        "afe_number": "25D001CJ",
        "description": "Drill SHIELDS-CANTRELL #1",
        "total_gross_estimate": 563603.25,
        "version_string": "S2",
        "supp_gross_estimate": 2333.1,
        "operator_wi": 65,
        "apc_partner_name": "John Ross Exploration Inc",
        "partner_wi": 20,
        "partner_status": "New",
        "op_status": "IAPP",
        "iapp_date": "2025-08-12",
        "last_mod_date": "2025-10-08",
        "legacy_chainID": 414,
        "legacy_afeid": 425,
        "chain_version": 3,
        "source_system_id": "e217aede-6af1-4696-8776-4d56d1ac16bf",
        "apc_partner_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_operator_id": null,
        "partner_status_date": null,
        "sortID": 153,
        "archived": false,
        "partner_archived": false,
        "source_partner_id": null,
        "doc_fetch_status": "pending",
        "doc_fetch_attempts": 0,
        "doc_last_fetch_at": null,
        "doc_last_error": null,
        "source_system_partner_id": "603ea163-a6b2-4f32-a8c5-67678401bf54",
        "apc_op_id": {
            "id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
            "name": "Corr and Whit Oils"
        },
        "well_name": "Many"
    },
    //Operated by Corr Whit & John Ross is Partner NOT ARCHIVED 
    {
        "id": "9f1ab2b4-3f58-4d6e-8365-f5126c4d0b4c",
        "created_at": "2025-10-22T17:10:47.867426+00:00",
        "afe_type": "DRILLING",
        "afe_number": "26D001CJ",
        "description": "Drill SHIELDS-CANTRELL #1",
        "total_gross_estimate": 563603.25,
        "version_string": null,
        "supp_gross_estimate": 0,
        "operator_wi": 25,
        "apc_partner_name": "John Ross Exploration Inc",
        "partner_wi": 50,
        "partner_status": "New",
        "op_status": "IAPP",
        "iapp_date": "2025-10-08",
        "last_mod_date": "2025-10-08",
        "legacy_chainID": 427,
        "legacy_afeid": 427,
        "chain_version": 1,
        "source_system_id": "8c7a4be7-e577-499d-8c7b-266a1549a020",
        "apc_partner_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_operator_id": null,
        "partner_status_date": null,
        "sortID": 154,
        "archived": false,
        "partner_archived": false,
        "source_partner_id": null,
        "doc_fetch_status": "pending",
        "doc_fetch_attempts": 0,
        "doc_last_fetch_at": null,
        "doc_last_error": null,
        "source_system_partner_id": "603ea163-a6b2-4f32-a8c5-67678401bf54",
        "apc_op_id": {
            "id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
            "name": "Corr and Whit Oils"
        },
        "well_name": "SHIELDS-CANTRELL #1"
    },
    //Operated by Nav Oil & Athena is Partner IS ARCHIVED 
    {
        "id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03z",
        "created_at": "2025-11-15T00:00:06.292558+00:00",
        "afe_type": "DRILLING",
        "afe_number": "A06D111NA",
        "description": "Drill DRAKE SURVEY-MASON #1",
        "total_gross_estimate": 275000,
        "version_string": null,
        "supp_gross_estimate": 0,
        "operator_wi": 80,
        "apc_partner_name": "Athena Minerals",
        "partner_wi": 20,
        "partner_status": "Viewed",
        "op_status": "FAPP",
        "iapp_date": "2025-11-14",
        "last_mod_date": "2025-11-14",
        "legacy_chainID": 176,
        "legacy_afeid": 176,
        "chain_version": 1,
        "source_system_id": "ba0c1c4f-81e5-4509-8089-6c9bc4919264",
        "apc_partner_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        "apc_operator_id": null,
        "partner_status_date": null,
        "sortID": 166,
        "archived": true,
        "partner_archived": true,
        "source_partner_id": null,
        "doc_fetch_status": "done",
        "doc_fetch_attempts": 2,
        "doc_last_fetch_at": "2025-12-30T20:09:51.423+00:00",
        "doc_last_error": null,
        "source_system_partner_id": "603ea163-a6b2-4f32-a8c5-67678401bf54",
        "apc_op_id": {
            "id": "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
            "name": "Navigator Corporation"
        },
        "well_name": "DRAKE SURVEY-MASON #1"
    },
    //Operated by Corr Whit & John Ross is Partner IS ARCHIVED 
    {
        "id": "88760c34-38b0-4bdd-a6d1-59376ec8c9be",
        "created_at": "2025-11-15T00:00:03.139299+00:00",
        "afe_type": "DRILLING",
        "afe_number": "A06D111CJ",
        "description": "Drill DRAKE SURVEY-MASON #1",
        "total_gross_estimate": 275000,
        "version_string": null,
        "supp_gross_estimate": 0,
        "operator_wi": 80,
        "apc_partner_name": "John Ross Exploration Inc",
        "partner_wi": 20,
        "partner_status": "Approved",
        "op_status": "FAPP",
        "iapp_date": "2025-11-14",
        "last_mod_date": "2025-11-14",
        "legacy_chainID": 176,
        "legacy_afeid": 176,
        "chain_version": 1,
        "source_system_id": "ba0c1c4f-81e5-4509-8089-6c9bc4919264",
        "apc_partner_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_operator_id": null,
        "partner_status_date": "2025-12-17T18:45:49.184+00:00",
        "sortID": 165,
        "archived": true,
        "partner_archived": true,
        "source_partner_id": null,
        "doc_fetch_status": "done",
        "doc_fetch_attempts": 2,
        "doc_last_fetch_at": "2025-12-30T20:09:48.995+00:00",
        "doc_last_error": null,
        "source_system_partner_id": "603ea163-a6b2-4f32-a8c5-67678401bf54",
        "apc_op_id": {
            "id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
            "name": "Corr and Whit Oils"
        },
        "well_name": "DRAKE SURVEY-MASON #1"
    },
    //Operated by Corr Whit & Athena is Partner IS ARCHIVED 
    {
        "id": "e74130a2-d985-4179-b0ff-9cc7e077d97e",
        "created_at": "2025-10-22T17:10:47.867426+00:00",
        "afe_type": "DRILLING",
        "afe_number": "A25D001CA",
        "description": "Drill SHIELDS-CANTRELL #1",
        "total_gross_estimate": 563603.25,
        "version_string": "S2",
        "supp_gross_estimate": 2333.1,
        "operator_wi": 65,
        "apc_partner_name": "Athena Minerals Inc.",
        "partner_wi": 15,
        "partner_status": "Viewed",
        "op_status": "IAPP",
        "iapp_date": "2025-08-12",
        "last_mod_date": "2025-10-08",
        "legacy_chainID": 414,
        "legacy_afeid": 425,
        "chain_version": 3,
        "source_system_id": "e217aede-6af1-4696-8776-4d56d1ac16bf",
        "apc_partner_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        "apc_operator_id": null,
        "partner_status_date": null,
        "sortID": 151,
        "archived": true,
        "partner_archived": true,
        "source_partner_id": null,
        "doc_fetch_status": "pending",
        "doc_fetch_attempts": 0,
        "doc_last_fetch_at": null,
        "doc_last_error": null,
        "source_system_partner_id": "475e4d12-8a0b-4264-933d-d960936852b2",
        "apc_op_id": {
            "id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
            "name": "Corr and Whit Oils"
        },
        "well_name": "Many"
    },
    //Operated by Corr Whit & Athena is Partner IS ARCHIVED 
    {
        "id": "f7247f99-2094-45b7-acb8-2bbd7070e261",
        "created_at": "2025-10-22T17:10:47.867426+00:00",
        "afe_type": "DRILLING",
        "afe_number": "A26D001CA",
        "description": "Drill SHIELDS-CANTRELL #1",
        "total_gross_estimate": 563603.25,
        "version_string": null,
        "supp_gross_estimate": 0,
        "operator_wi": 25,
        "apc_partner_name": "Athena Minerals Inc.",
        "partner_wi": 25,
        "partner_status": "Viewed",
        "op_status": "IAPP",
        "iapp_date": "2025-10-08",
        "last_mod_date": "2025-10-08",
        "legacy_chainID": 427,
        "legacy_afeid": 427,
        "chain_version": 1,
        "source_system_id": "8c7a4be7-e577-499d-8c7b-266a1549a020",
        "apc_partner_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        "apc_operator_id": null,
        "partner_status_date": null,
        "sortID": 152,
        "archived": true,
        "partner_archived": true,
        "source_partner_id": null,
        "doc_fetch_status": "pending",
        "doc_fetch_attempts": 0,
        "doc_last_fetch_at": null,
        "doc_last_error": null,
        "source_system_partner_id": "475e4d12-8a0b-4264-933d-d960936852b2",
        "apc_op_id": {
            "id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
            "name": "Corr and Whit Oils"
        },
        "well_name": "SHIELDS-CANTRELL #1"
    },
    //Operated by Corr Whit & John Ross is Partner IS ARCHIVED 
    {
        "id": "34d2bd01-d43b-4e3a-a586-34f0297a8008",
        "created_at": "2025-10-22T17:10:47.867426+00:00",
        "afe_type": "DRILLING",
        "afe_number": "A25D001CJ",
        "description": "Drill SHIELDS-CANTRELL #1",
        "total_gross_estimate": 563603.25,
        "version_string": "S2",
        "supp_gross_estimate": 2333.1,
        "operator_wi": 65,
        "apc_partner_name": "John Ross Exploration Inc",
        "partner_wi": 20,
        "partner_status": "New",
        "op_status": "IAPP",
        "iapp_date": "2025-08-12",
        "last_mod_date": "2025-10-08",
        "legacy_chainID": 414,
        "legacy_afeid": 425,
        "chain_version": 3,
        "source_system_id": "e217aede-6af1-4696-8776-4d56d1ac16bf",
        "apc_partner_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_operator_id": null,
        "partner_status_date": null,
        "sortID": 153,
        "archived": true,
        "partner_archived": true,
        "source_partner_id": null,
        "doc_fetch_status": "pending",
        "doc_fetch_attempts": 0,
        "doc_last_fetch_at": null,
        "doc_last_error": null,
        "source_system_partner_id": "603ea163-a6b2-4f32-a8c5-67678401bf54",
        "apc_op_id": {
            "id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
            "name": "Corr and Whit Oils"
        },
        "well_name": "Many"
    },
    //Operated by Corr Whit & John Ross is Partner IS ARCHIVED 
    {
        "id": "9f4ab2b4-3f58-4d6e-8365-f5126c4d0b4c",
        "created_at": "2025-10-22T17:10:47.867426+00:00",
        "afe_type": "DRILLING",
        "afe_number": "A26D001CJ",
        "description": "Drill SHIELDS-CANTRELL #1",
        "total_gross_estimate": 563603.25,
        "version_string": null,
        "supp_gross_estimate": 0,
        "operator_wi": 25,
        "apc_partner_name": "John Ross Exploration Inc",
        "partner_wi": 50,
        "partner_status": "New",
        "op_status": "IAPP",
        "iapp_date": "2025-10-08",
        "last_mod_date": "2025-10-08",
        "legacy_chainID": 427,
        "legacy_afeid": 427,
        "chain_version": 1,
        "source_system_id": "8c7a4be7-e577-499d-8c7b-266a1549a020",
        "apc_partner_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_operator_id": null,
        "partner_status_date": null,
        "sortID": 154,
        "archived": true,
        "partner_archived": true,
        "source_partner_id": null,
        "doc_fetch_status": "pending",
        "doc_fetch_attempts": 0,
        "doc_last_fetch_at": null,
        "doc_last_error": null,
        "source_system_partner_id": "603ea163-a6b2-4f32-a8c5-67678401bf54",
        "apc_op_id": {
            "id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
            "name": "Corr and Whit Oils"
        },
        "well_name": "SHIELDS-CANTRELL #1"
    }
];