import type { AFEType, EstimatesSupabaseType } from "../../src/types/interfaces";

export const singleAFE: AFEType[] = [{
    id: '123e4567-e89b-12d3-a456-426614174000',
    operator: '123e4567-e89b-12d3-a456-426614174000',
    created_at: 'May 1',
    afe_type: 'Drilling',
    afe_number: 'TESTNum1',
    description: 'Desc',
    total_gross_estimate: 100,
    version_string: '',
    supp_gross_estimate: 0,
    operator_wi: 10,
    partnerID: '',
    partner_name: 'PartnerNaem',
    partner_wi: 23,
    partner_status: 'New',
    op_status: 'IAPP',
    iapp_date: 'May5',
    last_mod_date: 'Jun3',
    legacy_chainID: 1,
    legacy_afeid: 2,
    chain_version: 1,
    source_system_id: 'ex ID',
    sortID: 1,
    partner_status_date: new Date(),
    apc_operator_id: 'opid',
}];

export const twoAFErecords: AFEType[] = [
    {
        id: '123e4567-e89b-12d3-a456-426614174000',
        operator: 'Nav Oil',
        created_at: 'May 1',
        afe_type: 'Drilling',
        afe_number: 'TESTNum1',
        description: 'Desc',
        total_gross_estimate: 100,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 10,
        partnerID: '',
        partner_name: 'Athena Minerals Inc.',
        partner_wi: 23,
        partner_status: 'New',
        op_status: 'IAPP',
        iapp_date: 'May5',
        last_mod_date: 'Jun3',
        legacy_chainID: 1,
        legacy_afeid: 2,
        chain_version: 1,
        source_system_id: 'ex ID',
        sortID: 1,
        partner_status_date: new Date(),
        apc_operator_id: 'opid',
    },
    {
        id: '123e4567-e89b-12d3-a456-426614174001',
        operator: 'Navigator Corporation',
        created_at: 'May 1',
        afe_type: 'Drilling',
        afe_number: 'TESTNum1',
        description: 'Desc',
        total_gross_estimate: 100,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 10,
        partnerID: '',
        partner_name: 'Partner 2',
        partner_wi: 23,
        partner_status: 'New',
        op_status: 'IAPP',
        iapp_date: 'May5',
        last_mod_date: 'Jun3',
        legacy_chainID: 1,
        legacy_afeid: 2,
        chain_version: 1,
        source_system_id: 'ex ID',
        sortID: 2,
        partner_status_date: new Date(),
        apc_operator_id: 'opid',
    }];

export const twoOperatedAFErecords: AFEType[] = [
    {
        id: '123e4567-e89b-12d3-a456-426614174000',
        operator: 'Navigator Corporation',
        created_at: 'May 1',
        afe_type: 'Drilling',
        afe_number: 'TESTNum1',
        description: 'Desc',
        total_gross_estimate: 100,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 10,
        partnerID: '',
        partner_name: 'Partner 1',
        partner_wi: 23,
        partner_status: 'New',
        op_status: 'IAPP',
        iapp_date: 'May5',
        last_mod_date: 'Jun3',
        legacy_chainID: 1,
        legacy_afeid: 2,
        chain_version: 1,
        source_system_id: 'ex ID',
        sortID: 1,
        partner_status_date: new Date(),
        apc_operator_id: 'opid',
    },
    {
        id: '123e4567-e89b-12d3-a456-426614174001',
        operator: 'Navigator Corporation',
        created_at: 'May 1',
        afe_type: 'Drilling',
        afe_number: 'TESTNum1',
        description: 'Desc',
        total_gross_estimate: 100,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 10,
        partnerID: '',
        partner_name: 'Partner 2',
        partner_wi: 23,
        partner_status: 'New',
        op_status: 'IAPP',
        iapp_date: 'May5',
        last_mod_date: 'Jun3',
        legacy_chainID: 1,
        legacy_afeid: 2,
        chain_version: 1,
        source_system_id: 'ex ID',
        sortID: 2,
        partner_status_date: new Date(),
     apc_operator_id: 'opid',
    }];

export const twoNonOperatedAFErecords: AFEType[] = [
    {
        id: '123e4567-e89b-12d3-a456-426614174000',
        operator: 'Nav Oil',
        created_at: 'May 1',
        afe_type: 'Drilling',
        afe_number: 'TESTNum1',
        description: 'Desc',
        total_gross_estimate: 100,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 10,
        partnerID: '',
        partner_name: 'Athena Minerals Inc.',
        partner_wi: 23,
        partner_status: 'New',
        op_status: 'IAPP',
        iapp_date: 'May5',
        last_mod_date: 'Jun3',
        legacy_chainID: 1,
        legacy_afeid: 2,
        chain_version: 1,
        source_system_id: 'ex ID',
        sortID: 1,
        partner_status_date: new Date(),
        apc_operator_id: 'opid',
    },
    {
        id: '123e4567-e89b-12d3-a456-426614174001',
        operator: 'Nav Oil',
        created_at: 'May 1',
        afe_type: 'Drilling',
        afe_number: 'TESTNum1',
        description: 'Desc',
        total_gross_estimate: 100,
        version_string: '',
        supp_gross_estimate: 0,
        operator_wi: 10,
        partnerID: '',
        partner_name: 'Athena Minerals Inc.',
        partner_wi: 23,
        partner_status: 'New',
        op_status: 'IAPP',
        iapp_date: 'May5',
        last_mod_date: 'Jun3',
        legacy_chainID: 1,
        legacy_afeid: 2,
        chain_version: 1,
        source_system_id: 'ex ID',
        sortID: 2,
        partner_status_date: new Date(),
        apc_operator_id: 'opid',
    }];

export const singleEstimateRecord: EstimatesSupabaseType[] = [
    {
        id: 1,
        amount_gross: 100,
        partner_wi: 20.00,
        partner_net_amount: 20.00,
        operator_account_number: 'OP.ACCT.NUM',
        operator_account_description: 'Mock account desc',
        operator_account_group: '1. DRILLING',
        partner_account_number: 'P.ACCT.NUM',
        partner_account_description: 'P ACCT DESC',
        partner_account_group: 'P ACCT GROUP'
    },
    {
        id: 1,
        amount_gross: 100,
        partner_wi: 20.00,
        partner_net_amount: 20.00,
        operator_account_number: 'OP.ACCT.NUM',
        operator_account_description: 'Mock account desc',
        operator_account_group: '1. DRILLING',
        partner_account_number: 'P.ACCT.NUM',
        partner_account_description: 'P ACCT DESC',
        partner_account_group: 'P ACCT GROUP'
    }
];

export const parterNewStatus: AFEType = {
    id: '123e4567-e89b-12d3-a456-426614174000',
    operator: '123e4567-e89b-12d3-a456-426614174000',
    created_at: 'May 1',
    afe_type: 'Drilling',
    afe_number: 'TESTNum1',
    description: 'Desc',
    total_gross_estimate: 100,
    version_string: '',
    supp_gross_estimate: 0,
    operator_wi: 10,
    partnerID: '',
    partner_name: 'PartnerNaem',
    partner_wi: 23,
    partner_status: 'New',
    op_status: 'IAPP',
    iapp_date: 'May5',
    last_mod_date: 'Jun3',
    legacy_chainID: 1,
    legacy_afeid: 2,
    chain_version: 1,
    source_system_id: 'ex ID',
    sortID: 1,
    partner_status_date: new Date(),
    apc_operator_id: 'opid',
};

export const parterViewStatus: AFEType = {
    id: '123e4567-e89b-12d3-a456-426614174000',
    operator: '123e4567-e89b-12d3-a456-426614174000',
    created_at: new Date(),
    afe_type: 'Drilling',
    afe_number: 'TESTNum1',
    description: 'Desc',
    total_gross_estimate: 100,
    version_string: '',
    supp_gross_estimate: 0,
    operator_wi: 10,
    partnerID: '',
    partner_name: 'PartnerNaem',
    partner_wi: 23,
    partner_status: 'Viewed',
    op_status: 'IAPP',
    iapp_date: 'May5',
    last_mod_date: 'Jun3',
    legacy_chainID: 1,
    legacy_afeid: 2,
    chain_version: 1,
    source_system_id: 'ex ID',
    sortID: 1,
    partner_status_date: new Date(),
    apc_operator_id: 'opid',
};
export const parterApprovedStatus: AFEType = {
    id: '123e4567-e89b-12d3-a456-426614174000',
    operator: '123e4567-e89b-12d3-a456-426614174000',
    created_at: 'May 1',
    afe_type: 'Drilling',
    afe_number: 'TESTNum1',
    description: 'Desc',
    total_gross_estimate: 100,
    version_string: '',
    supp_gross_estimate: 0,
    operator_wi: 10,
    partnerID: '',
    partner_name: 'PartnerNaem',
    partner_wi: 23,
    partner_status: 'Approved',
    op_status: 'IAPP',
    iapp_date: 'May5',
    last_mod_date: 'Jun3',
    legacy_chainID: 1,
    legacy_afeid: 2,
    chain_version: 1,
    source_system_id: 'ex ID',
    sortID: 1,
    partner_status_date: new Date(),
    apc_operator_id: 'opid',
};
export const parterRejectedStatus: AFEType = {
    id: '123e4567-e89b-12d3-a456-426614174000',
    operator: '123e4567-e89b-12d3-a456-426614174000',
    created_at: 'May 1',
    afe_type: 'Drilling',
    afe_number: 'TESTNum1',
    description: 'Desc',
    total_gross_estimate: 100,
    version_string: '',
    supp_gross_estimate: 0,
    operator_wi: 10,
    partnerID: '',
    partner_name: 'PartnerNaem',
    partner_wi: 23,
    partner_status: 'Rejected',
    op_status: 'IAPP',
    iapp_date: 'May5',
    last_mod_date: 'Jun3',
    legacy_chainID: 1,
    legacy_afeid: 2,
    chain_version: 1,
    source_system_id: 'ex ID',
    sortID: 1,
    partner_status_date: new Date(),
    apc_operator_id: 'opid',
};