export const rows = {
    "Rows": [
        {
            "DocumentId": "fed879ab-a060-4f33-9d93-b9ad386d4ebd",
            "ListItemId": "292448b4-670e-40cb-9d0a-4d650357f806",
            "StatusColor": "PartiallyApproved",
            "Data": [
                "fed879ab-a060-4f33-9d93-b9ad386d4ebd",
                "25D001",
                "Drill SHIELDS-CANTRELL #1",
                "DRILLING",
                "561,270.15",
                "S1",
                "15,270.15",
                "Navigator Corporation",
                "65.00000000",
                "475e4d12-8a0b-4264-933d-d960936852b2",
                "Athena Minerals Inc.",
                "15.00000000",
                "No Status",
                "IAPP",
                "2025-04-22 13:42",
                "2025-04-22 13:42",
                "414",
                "415",
                "2"
            ],
            "RawData": [
                "fed879ab-a060-4f33-9d93-b9ad386d4ebd",
                "25D001",
                "Drill SHIELDS-CANTRELL #1",
                "DRILLING",
                561270.15000000000000,
                "S1",
                15270.15,
                "Navigator Corporation",
                65.00000000000000,
                "475e4d12-8a0b-4264-933d-d960936852b2",
                "Athena Minerals Inc.",
                15.00000000000000,
                "No Status",
                "IAPP",
                "2025-04-22T19:42:42.6265229Z",
                "2025-04-22T19:42:42.6635477Z",
                414,
                415,
                2
            ],
            "Editable": [
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false
            ],
            "Flags": [],
            "Valid": [
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true
            ]
        },
        {
            "DocumentId": "fed879ab-a060-4f33-9d93-b9ad386d4ebd",
            "ListItemId": "72370bcb-ae14-4eb2-8e2d-27f023f1b4fa",
            "StatusColor": "PartiallyApproved",
            "Data": [
                "fed879ab-a060-4f33-9d93-b9ad386d4ebd",
                "25D001",
                "Drill SHIELDS-CANTRELL #1",
                "DRILLING",
                "561,270.15",
                "S1",
                "15,270.15",
                "Navigator Corporation",
                "65.00000000",
                "603ea163-a6b2-4f32-a8c5-67678401bf54",
                "John Ross Exploration Inc",
                "20.00000000",
                "No Status",
                "IAPP",
                "2025-04-22 13:42",
                "2025-04-22 13:42",
                "414",
                "415",
                "2"
            ],
            "RawData": [
                "fed879ab-a060-4f33-9d93-b9ad386d4ebd",
                "25D001",
                "Drill SHIELDS-CANTRELL #1",
                "DRILLING",
                561270.15000000000000,
                "S1",
                15270.15,
                "Navigator Corporation",
                65.00000000000000,
                "603ea163-a6b2-4f32-a8c5-67678401bf54",
                "John Ross Exploration Inc",
                20.00000000000000,
                "No Status",
                "IAPP",
                "2025-04-22T19:42:42.6265229Z",
                "2025-04-22T19:42:42.6635477Z",
                414,
                415,
                2
            ],
            "Editable": [
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false
            ],
            "Flags": [],
            "Valid": [
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true
            ]
        }
    ],
    "Columns": [
        {
            "UniqueDisplayName": "Document Id",
            "ColumnId": "DOCUMENT_ID",
            "Name": "Document Id",
            "NameIsUserProvided": false,
            "Type": "Text",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "AFE Number",
            "ColumnId": "AFENUMBER_DOC/AFENUMBER",
            "Name": "AFE Number",
            "NameIsUserProvided": false,
            "Type": "Text",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Description",
            "ColumnId": "DESCRIPTION",
            "Name": "Description",
            "NameIsUserProvided": false,
            "Type": "Text",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": [
                "DESCRIPTION"
            ]
        },
        {
            "UniqueDisplayName": "AFE Type - Value",
            "ColumnId": "CUSTOM/AFE_TYPE/VALUE",
            "Name": "Value",
            "NameIsUserProvided": false,
            "Type": "Text",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Total Gross Estimate",
            "ColumnId": "TOTAL_GROSS_ESTIMATE",
            "Name": "Total Gross Estimate",
            "NameIsUserProvided": false,
            "Type": "Decimal",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": true,
            "DecimalPlaces": 2,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Ver",
            "ColumnId": "VERSION_STRING",
            "Name": "Ver",
            "NameIsUserProvided": false,
            "Type": "Text",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Supplemental Gross Estimate",
            "ColumnId": "SUPPLEMENTAL_GROSS_ESTIMATE",
            "Name": "Supplemental Gross Estimate",
            "NameIsUserProvided": false,
            "Type": "Decimal",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": true,
            "DecimalPlaces": 2,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Operator - Company",
            "ColumnId": "OPERATING_COMPANY/COMNAME",
            "Name": "Company",
            "NameIsUserProvided": false,
            "Type": "Text",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Operator WI (%)",
            "ColumnId": "OPERATOR_WI",
            "Name": "Operator WI (%)",
            "NameIsUserProvided": false,
            "Type": "Decimal",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 8,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Partners - Company - Document Id",
            "ColumnId": "$COMPANY/DOCUMENT_ID",
            "Name": "Document Id",
            "NameIsUserProvided": false,
            "Type": "Text",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Partners - Company - Company",
            "ColumnId": "$COMPANY/COMNAME",
            "Name": "Company",
            "NameIsUserProvided": false,
            "Type": "Text",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Partners - Working Interest",
            "ColumnId": "$WI_PERCENT",
            "Name": "Working Interest",
            "NameIsUserProvided": false,
            "Type": "Decimal",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 8,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Partners - Status",
            "ColumnId": "$STATUS",
            "Name": "Status",
            "NameIsUserProvided": false,
            "Type": "Document",
            "HasValueList": true,
            "MultiSelectSearch": true,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [
                [
                    "Affirmative",
                    "<span class=\"label label-default\" style=\"foreground-color: #FFFFFF; background-color: #5CB85C\">Affirmative</span>"
                ],
                [
                    "Rejected",
                    "<span class=\"label label-default\" style=\"foreground-color: #FFFFFF; background-color: #D9534F\">Rejected</span>"
                ],
                [
                    "Deemed Affirmative",
                    "<span class=\"label label-default\" style=\"foreground-color: #FFFFFF; background-color: #5BC0DE\">Deemed Affirmative</span>"
                ],
                [
                    "Approved",
                    "<span class=\"label label-default\" style=\"foreground-color: #FFFFFF; background-color: #5CB55C\">Approved</span>"
                ],
                [
                    "Abstain",
                    "<span class=\"label label-default\" style=\"foreground-color: #FFFFFF; background-color: #F0AD4E\">Abstain</span>"
                ],
                [
                    "No Status",
                    "<span class=\"label label-default\" style=\"foreground-color: #FFFFFF; background-color: #999999\">No Status</span>"
                ],
                [
                    "Negative",
                    "<span class=\"label label-default\" style=\"foreground-color: #FFFFFF; background-color: #D9534F\">Negative</span>"
                ]
            ],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Status",
            "ColumnId": "STATUS",
            "Name": "Status",
            "NameIsUserProvided": false,
            "Type": "Text",
            "HasValueList": true,
            "MultiSelectSearch": true,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Internal Approval Date",
            "ColumnId": "INTERNAL_APPROVAL_DATE",
            "Name": "Internal Approval Date",
            "NameIsUserProvided": false,
            "Type": "Date",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Last Modified - Date",
            "ColumnId": "!LAST_MODIFIED_DATE",
            "Name": "Last Modified Date",
            "NameIsUserProvided": false,
            "Type": "Date",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Legacy AFE Chain ID",
            "ColumnId": "LEGACY_CHAINID",
            "Name": "Legacy AFE Chain ID",
            "NameIsUserProvided": false,
            "Type": "Integer",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Legacy AFE ID",
            "ColumnId": "LEGACY_AFEID",
            "Name": "Legacy AFE ID",
            "NameIsUserProvided": false,
            "Type": "Integer",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        },
        {
            "UniqueDisplayName": "Chain Version",
            "ColumnId": "CHAIN_VERSION",
            "Name": "Chain Version",
            "NameIsUserProvided": false,
            "Type": "Integer",
            "HasValueList": false,
            "MultiSelectSearch": false,
            "IsCurrency": false,
            "DecimalPlaces": 0,
            "ValueMap": [],
            "Valid": true,
            "UnzonedDateTime": false,
            "UpdatablePath": []
        }
    ],
    "TotalRowCount": 488,
    "FilteredRowCount": 2,
    "ElapsedTimeMS": 22.4557,
    "SummaryRow": [
        null,
        null,
        null,
        null,
        "1,122,540.30",
        null,
        "30,540.30",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    "StickyColumnsSaveKey": "BROWSE_STICKY_TYPE_AFE_AFE/PARTNER"
}

export const docHandleResponse = {
    "DocumentHandle": "ZeUO5n0TVEkzYcpBzYQC",
    "IsDeleted": false,
    "IsHistoricalVersion": false
}

export const twoDocHandleResponse = {
    Rows: [
        {
            "DocumentHandle": "ZeUO5n0TVEkzYcpBzYQC",
            "IsDeleted": false,
            "IsHistoricalVersion": false
        },
        {
            "DocumentHandle": "ZeUO5n0TVEkzYcpBzYQC",
            "IsDeleted": false,
            "IsHistoricalVersion": false,
        }
    ]


}