//The Rachel Green user has permissions for the Operator of Corr and Whit Oils Company for roles 2, 4, 8
// AND John Ross Non-Op AFEs with roles 3,9,5,6

import type { UserProfileRecordSupabaseType } from "src/types/interfaces";

export const apc_op_id_CW = '3b34a78a-13ad-40b5-aecd-268d56dd5e0d';
export const apc_part_id_John = '8ed0a285-0011-4f56-962f-c46bc0889d1b';
export const apc_part_id_Athena = '626390b5-6f63-4caa-a0aa-b333a15eaf59';
const userID1 = '13e69340-d14c-45a9-96a8-142795925487'

//Rachel has Corr Whit oils 2, 4, 8, John Ross 3,5,9,6
export const loggedInUserRachelGreen: UserProfileRecordSupabaseType = {
    firstName: 'Rachel',
    lastName: 'Green',
    email: 'elizabeth.rider.shaw@gmail.com',
    active: true,
    is_super_user: false,
    operatorRoles: [
        {
            apc_name: 'Corr and Whit Oils Company',
            apc_address: {
                address_active: true,
                id: 66,
                street: '6789 S Blvd',
                suite: '',
                city: 'Houston',
                state: 'Texas',
                zip: '90078',
                country: 'United States'
            },
            user_id: userID1,
            user_firstname: 'Rachel',
            user_lastName: 'Green',
            user_email: 'elizabeth.rider.shaw@gmail.com',
            user_active: true,
            is_op_permission: true,
            is_partner_permission: false,
            id: 120,
            role: 2,
            active: true,
            apc_id: apc_op_id_CW,
            apc_address_id: 66
        },
        {
            apc_name: 'Corr and Whit Oils Company',
            apc_address: {
                address_active: true,
                id: 66,
                street: '6789 S Blvd',
                suite: '',
                city: 'Houston',
                state: 'Texas',
                zip: '90078',
                country: 'United States'
            },
            user_id: userID1,
            user_firstname: 'Rachel',
            user_lastName: 'Green',
            user_email: 'elizabeth.rider.shaw@gmail.com',
            user_active: true,
            is_op_permission: true,
            is_partner_permission: false,
            id: 120,
            role: 4,
            active: true,
            apc_id: apc_op_id_CW,
            apc_address_id: 66
        },
        {
            apc_name: 'Corr and Whit Oils Company',
            apc_address: {
                address_active: true,
                id: 66,
                street: '6789 S Blvd',
                suite: '',
                city: 'Houston',
                state: 'Texas',
                zip: '90078',
                country: 'United States'
            },
            user_id: userID1,
            user_firstname: 'Rachel',
            user_lastName: 'Green',
            user_email: 'elizabeth.rider.shaw@gmail.com',
            user_active: true,
            is_op_permission: true,
            is_partner_permission: false,
            id: 120,
            role: 8,
            active: true,
            apc_id: apc_op_id_CW,
            apc_address_id: 66
        },
    ],
    partnerRoles: [
        {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 35,
        role: 3,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 72,
        role: 9,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 74,
        role: 5,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 185,
        role: 6,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    }
    
    ],
};

export const loggedInUserRachelGreenWithUserId: UserProfileRecordSupabaseType = {
    firstName: 'Rachel',
    lastName: 'Green',
    email: 'elizabeth.rider.shaw@gmail.com',
    active: true,
    is_super_user: false,
    user_id: '13e69340-d14c-45a9-96a8-142795925487',
    operatorRoles: [
        {
            apc_name: 'Corr and Whit Oils Company',
            apc_address: {
                address_active: true,
                id: 66,
                street: '6789 S Blvd',
                suite: '',
                city: 'Houston',
                state: 'Texas',
                zip: '90078',
                country: 'United States'
            },
            user_id: userID1,
            user_firstname: 'Rachel',
            user_lastName: 'Green',
            user_email: 'elizabeth.rider.shaw@gmail.com',
            user_active: true,
            is_op_permission: true,
            is_partner_permission: false,
            id: 120,
            role: 2,
            active: true,
            apc_id: apc_op_id_CW,
            apc_address_id: 66
        },
        {
            apc_name: 'Corr and Whit Oils Company',
            apc_address: {
                address_active: true,
                id: 66,
                street: '6789 S Blvd',
                suite: '',
                city: 'Houston',
                state: 'Texas',
                zip: '90078',
                country: 'United States'
            },
            user_id: userID1,
            user_firstname: 'Rachel',
            user_lastName: 'Green',
            user_email: 'elizabeth.rider.shaw@gmail.com',
            user_active: true,
            is_op_permission: true,
            is_partner_permission: false,
            id: 120,
            role: 4,
            active: true,
            apc_id: apc_op_id_CW,
            apc_address_id: 66
        },
        {
            apc_name: 'Corr and Whit Oils Company',
            apc_address: {
                address_active: true,
                id: 66,
                street: '6789 S Blvd',
                suite: '',
                city: 'Houston',
                state: 'Texas',
                zip: '90078',
                country: 'United States'
            },
            user_id: userID1,
            user_firstname: 'Rachel',
            user_lastName: 'Green',
            user_email: 'elizabeth.rider.shaw@gmail.com',
            user_active: true,
            is_op_permission: true,
            is_partner_permission: false,
            id: 120,
            role: 8,
            active: true,
            apc_id: apc_op_id_CW,
            apc_address_id: 66
        },
    ],
    partnerRoles: [
        {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 35,
        role: 3,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 72,
        role: 9,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 74,
        role: 5,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 185,
        role: 6,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    }
    
    ],
};
//Ross Geller has 3,5,9,6
export const loggedInUserRossGeller: UserProfileRecordSupabaseType = {
    firstName: 'Ross',
    lastName: 'Geller',
    email: 'elizabeth.rider.shaw@gmail.com',
    active: true,
    is_super_user: false,
    operatorRoles: [],
    partnerRoles: [
        {
        apc_name: 'Athena',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Ross Geller',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 35,
        role: 3,
        active: true,
        apc_id: apc_part_id_Athena,
        apc_address_id: 10
    },
    {
        apc_name: 'Athena',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Ross',
        user_lastName: 'Geller',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 72,
        role: 9,
        active: true,
        apc_id: apc_part_id_Athena,
        apc_address_id: 10
    },
    {
        apc_name: 'Athena',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Ross',
        user_lastName: 'Geller',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 74,
        role: 5,
        active: true,
        apc_id: apc_part_id_Athena,
        apc_address_id: 10
    },
    {
        apc_name: 'Athena',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Ross',
        user_lastName: 'Geller',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 185,
        role: 6,
        active: true,
        apc_id: apc_part_id_Athena,
        apc_address_id: 10
    }
    
    ],
};

export const loggedInUserRachelGreenNoRole2: UserProfileRecordSupabaseType = {
    firstName: 'Rachel',
    lastName: 'Green',
    email: 'elizabeth.rider.shaw@gmail.com',
    active: true,
    is_super_user: false,
    operatorRoles: [
        {
            apc_name: 'Corr and Whit Oils Company',
            apc_address: {
                address_active: true,
                id: 66,
                street: '6789 S Blvd',
                suite: '',
                city: 'Houston',
                state: 'Texas',
                zip: '90078',
                country: 'United States'
            },
            user_id: userID1,
            user_firstname: 'Rachel',
            user_lastName: 'Green',
            user_email: 'elizabeth.rider.shaw@gmail.com',
            user_active: true,
            is_op_permission: true,
            is_partner_permission: false,
            id: 120,
            role: 4,
            active: true,
            apc_id: apc_op_id_CW,
            apc_address_id: 66
        },
        {
            apc_name: 'Corr and Whit Oils Company',
            apc_address: {
                address_active: true,
                id: 66,
                street: '6789 S Blvd',
                suite: '',
                city: 'Houston',
                state: 'Texas',
                zip: '90078',
                country: 'United States'
            },
            user_id: userID1,
            user_firstname: 'Rachel',
            user_lastName: 'Green',
            user_email: 'elizabeth.rider.shaw@gmail.com',
            user_active: true,
            is_op_permission: true,
            is_partner_permission: false,
            id: 120,
            role: 8,
            active: true,
            apc_id: apc_op_id_CW,
            apc_address_id: 66
        },
    ],
    partnerRoles: [
        {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 35,
        role: 3,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 72,
        role: 9,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 74,
        role: 5,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 185,
        role: 6,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    }
    
    ],
};

export const loggedInUserRachelGreenCannotEditUsersNoRole4or5: UserProfileRecordSupabaseType = {
    firstName: 'Rachel',
    lastName: 'Green',
    email: 'elizabeth.rider.shaw@gmail.com',
    active: true,
    is_super_user: false,
    operatorRoles: [
        {
            apc_name: 'Corr and Whit Oils Company',
            apc_address: {
                address_active: true,
                id: 66,
                street: '6789 S Blvd',
                suite: '',
                city: 'Houston',
                state: 'Texas',
                zip: '90078',
                country: 'United States'
            },
            user_id: userID1,
            user_firstname: 'Rachel',
            user_lastName: 'Green',
            user_email: 'elizabeth.rider.shaw@gmail.com',
            user_active: true,
            is_op_permission: true,
            is_partner_permission: false,
            id: 120,
            role: 2,
            active: true,
            apc_id: apc_op_id_CW,
            apc_address_id: 66
        },
        {
            apc_name: 'Corr and Whit Oils Company',
            apc_address: {
                address_active: true,
                id: 66,
                street: '6789 S Blvd',
                suite: '',
                city: 'Houston',
                state: 'Texas',
                zip: '90078',
                country: 'United States'
            },
            user_id: userID1,
            user_firstname: 'Rachel',
            user_lastName: 'Green',
            user_email: 'elizabeth.rider.shaw@gmail.com',
            user_active: true,
            is_op_permission: true,
            is_partner_permission: false,
            id: 120,
            role: 8,
            active: true,
            apc_id: apc_op_id_CW,
            apc_address_id: 66
        },
    ],
    partnerRoles: [
        {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 35,
        role: 3,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 72,
        role: 9,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 185,
        role: 6,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    }
    
    ],
};

export const loggedInUserRachelGreenCannotEditUsersNoRole4or5or8or9: UserProfileRecordSupabaseType = {
    firstName: 'Rachel',
    lastName: 'Green',
    email: 'elizabeth.rider.shaw@gmail.com',
    active: true,
    is_super_user: false,
    operatorRoles: [
        {
            apc_name: 'Corr and Whit Oils Company',
            apc_address: {
                address_active: true,
                id: 66,
                street: '6789 S Blvd',
                suite: '',
                city: 'Houston',
                state: 'Texas',
                zip: '90078',
                country: 'United States'
            },
            user_id: userID1,
            user_firstname: 'Rachel',
            user_lastName: 'Green',
            user_email: 'elizabeth.rider.shaw@gmail.com',
            user_active: true,
            is_op_permission: true,
            is_partner_permission: false,
            id: 120,
            role: 2,
            active: true,
            apc_id: apc_op_id_CW,
            apc_address_id: 66
        },
        
    ],
    partnerRoles: [
        {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 35,
        role: 3,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 185,
        role: 6,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    }
    
    ],
};

export const loggedInUserNoAFEViewRights: UserProfileRecordSupabaseType = {
    firstName: 'Rachel',
    lastName: 'Green',
    email: 'elizabeth.rider.shaw@gmail.com',
    active: true,
    is_super_user: false,
    operatorRoles: [
        {
            apc_name: 'Corr and Whit Oils Company',
            apc_address: {
                address_active: true,
                id: 66,
                street: '6789 S Blvd',
                suite: '',
                city: 'Houston',
                state: 'Texas',
                zip: '90078',
                country: 'United States'
            },
            user_id: userID1,
            user_firstname: 'Rachel',
            user_lastName: 'Green',
            user_email: 'elizabeth.rider.shaw@gmail.com',
            user_active: true,
            is_op_permission: true,
            is_partner_permission: false,
            id: 120,
            role: 4,
            active: true,
            apc_id: apc_op_id_CW,
            apc_address_id: 66
        },
        {
            apc_name: 'Corr and Whit Oils Company',
            apc_address: {
                address_active: true,
                id: 66,
                street: '6789 S Blvd',
                suite: '',
                city: 'Houston',
                state: 'Texas',
                zip: '90078',
                country: 'United States'
            },
            user_id: userID1,
            user_firstname: 'Rachel',
            user_lastName: 'Green',
            user_email: 'elizabeth.rider.shaw@gmail.com',
            user_active: true,
            is_op_permission: true,
            is_partner_permission: false,
            id: 120,
            role: 8,
            active: true,
            apc_id: apc_op_id_CW,
            apc_address_id: 66
        },
    ],
    partnerRoles: [
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 72,
        role: 9,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 74,
        role: 5,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    },
    {
        apc_name: 'John Ross',
        apc_address: {
            address_active: true,
            id: 10,
            street: '2900 S Emerson St',
            suite:'878',
            city: 'Englewood',
            state: 'CO',
            zip: '80093',
            country: 'United States'
        },
        user_id: userID1,
        user_firstname: 'Rachel',
        user_lastName: 'Green',
        user_email: 'elizabeth.rider.shaw@gmail.com',
        user_active: true,
        is_op_permission: false,
        is_partner_permission: true,
        id: 185,
        role: 6,
        active: true,
        apc_id: apc_part_id_John,
        apc_address_id: 10
    }
    
    ],
};

//NEW TEST CASES FOR RACHEL GREEN

// SINGLE AFE RETURN
export const singleAFEResultSupabase = 
    {
        "id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03W",
        "created_at": "2025-11-15T00:00:06.292558+00:00",
        "afe_type": "DRILLING",
        "afe_number": "DR26NAVAT",
        "description": "Drill DRAKE SURVEY-MASON #1",
        "total_gross_estimate": 275000,
        "version_string": null,
        "supp_gross_estimate": 0,
        "operator_wi": 80,
        "apc_partner_name": "Athena Minerals",
        "partner_wi": 20,
        "partner_status": "Viewed",
        "op_status": "FAPP",
        "iapp_date": "2025-11-14",
        "last_mod_date": "2025-11-14",
        "legacy_chainID": 176,
        "legacy_afeid": 176,
        "chain_version": 1,
        "source_system_id": "ba0c1c4f-81e5-4509-8089-6c9bc4919264",
        "apc_partner_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        "apc_operator_id": null,
        "partner_status_date": null,
        "sortID": 166,
        "archived": false,
        "partner_archived": false,
        "source_partner_id": null,
        "doc_fetch_status": "done",
        "doc_fetch_attempts": 2,
        "doc_last_fetch_at": "2025-12-30T20:09:51.423+00:00",
        "doc_last_error": null,
        "source_system_partner_id": "603ea163-a6b2-4f32-a8c5-67678401bf54",
        "apc_op_id": {
            "id": apc_op_id_CW,
            "name": "Corr and Whit Oils"
        },
        "well_name": "DRAKE SURVEY-MASON #1"
    };
export const singleAFEEstimatesResponse = [
    {
    "id": 3564,
    "created_at": "2025-11-15T00:00:06.528367+00:00",
    "source_system_id": "ba0c1c4f-81e5-4509-8089-6c9bc4919264",
    "apc_partner_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
    "operator_account_number": "9210.247",
    "operator_account_description": "LABOUR",
    "operator_account_group": "1. DRILLING",
    "amount_gross": 275000,
    "partner_wi": 20,
    "partner_net_amount": 55000,
    "apc_operator_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
    "partner_account_number": null,
    "partner_account_description": null,
    "partner_account_group": null,
    "gl_code_crosswalk_id": 30,
    "apc_afe_id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03W",
    "gl_processed_id_operator": 20
},
{
    "id": 3566,
    "created_at": "2025-11-15T00:00:06.528367+00:00",
    "source_system_id": "ba0c1c4f-81e5-4509-8089-6c9bc4919264",
    "apc_partner_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
    "operator_account_number": "9210.247",
    "operator_account_description": "LABOUR",
    "operator_account_group": "2. DRILLING",
    "amount_gross": 375000,
    "partner_wi": 30,
    "partner_net_amount": 35000,
    "apc_operator_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
    "partner_account_number": null,
    "partner_account_description": null,
    "partner_account_group": null,
    "gl_code_crosswalk_id": 20,
    "apc_afe_id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03W",
    "gl_processed_id_operator": 30
}
];
export const singleAFEWellResponse = [
    {
    "id": 129,
    "created_at": "2025-11-15T00:00:07.833166+00:00",
    "apc_op_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
    "source_system_id": "ba0c1c4f-81e5-4509-8089-6c9bc4919264",
    "is_primary": false,
    "well_name": "DRAKE SURVEY-MASON #1",
    "description": null,
    "well_number": null
}
];
export const singleAFEHistoryResponse = [
    {
        "id": 219,
        "afe_id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03d",
        "created_at": "2026-01-26T03:38:54.690047+00:00",
        "description": "Queen Elizabeth downloaded the AFE attachment Execute Demo Outline for AFE# 06D111",
        "type": "file download",
        "user_id": {
            "last_name": "Elizabeth",
            "first_name": "Queen"
        }
    },
    {
        "id": 190,
        "afe_id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03d",
        "created_at": "2026-01-06T22:19:29.310825+00:00",
        "description": "Yes I did",
        "type": "comment",
        "user_id": {
            "last_name": "Elizabeth",
            "first_name": "Queen"
        }
    },
    {
        "id": 170,
        "afe_id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03d",
        "created_at": "2025-11-29T05:42:39.16366+00:00",
        "description": "The Partner Status on the AFE changed from New to Viewed",
        "type": "action",
        "user_id": {
            "last_name": "Elizabeth",
            "first_name": "Queen"
        }
    },
    {
        "id": 220,
        "afe_id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03d",
        "created_at": "2026-01-26T03:57:13.160237+00:00",
        "description": "Queen Elizabeth viewed the AFE attachment ElizabethShawResume for AFE# 06D111",
        "type": "file viewed",
        "user_id": {
            "last_name": "Elizabeth",
            "first_name": "Queen"
        }
    }
];
export const singleAFEAttachmentResponse = [
    {
        "id": 6222,
        "created_at": "2025-11-20T21:25:04.484064+00:00",
        "apc_afe_id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03d",
        "apc_op_id": {
            "name": "Navigator Corporation"
        },
        "apc_partner_id": null,
        "storage_path": "afe/null/9dadae6e-a301-4066-aab4-c329ef1a8e72.xlsx",
        "filename": "Book1_v1.xlsx",
        "filename_display": "Book1",
        "mimetype": "xlsx",
        "byte_size": 17424,
        "checksum": "f06c01b8bef446b9a574dfe6eadc0882dc3bdd36071c52473727b1fecf11c784",
        "source_doc_id": "ba0c1c4f-81e5-4509-8089-6c9bc4919264",
        "isForm": false,
        "isAttachment": true,
        "documentDate": "2025-11-19T21:43:36+00:00",
        "isNonOpSignedAFE": false
    }
];

export const singleAFEDocResponse = [
    {
        "id": 6224,
        "created_at": "2025-12-29T23:51:15.939759+00:00",
        "apc_afe_id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03d",
        "apc_op_id": {
            "name": "Navigator Corporation"
        },
        "apc_partner_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "storage_path": "afe/4b6cebbf-ca88-4e9e-8479-dd50cc13e03d/0c386c3e-87bd-45a0-ae03-6eaf7b4043cd.pdf",
        "filename": "Navigator Corporation AFE for John Ross Exploration Inc.pdf",
        "filename_display": "Navigator Corporation AFE for John Ross Exploration Inc",
        "mimetype": "pdf",
        "byte_size": 32731,
        "checksum": "a57733529a1a304e4ea535d6da3c0853d527a7d4cd457a3bb6c2cdb09f82d4c2",
        "source_doc_id": "ba0c1c4f-81e5-4509-8089-6c9bc4919264",
        "isForm": true,
        "isAttachment": false,
        "documentDate": "2025-12-29T23:51:14.135939+00:00",
        "isNonOpSignedAFE": false
    }
];

export const singleAFESignedResponse = [
    {
        "id": 6233,
        "created_at": "2026-01-26T04:34:59.903053+00:00",
        "apc_afe_id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03d",
        "apc_op_id": {
            "name": "Navigator Corporation"
        },
        "apc_partner_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "storage_path": "afe/0.454131682418625.docx",
        "filename": "ElizabethShaw2024.docx",
        "filename_display": "ElizabethShaw2024",
        "mimetype": "docx",
        "byte_size": 25221,
        "checksum": null,
        "source_doc_id": null,
        "isForm": false,
        "isAttachment": false,
        "documentDate": "2026-01-26T04:34:59.773+00:00",
        "isNonOpSignedAFE": true
    },
    {
        "id": 6235,
        "created_at": "2026-01-26T04:39:11.837635+00:00",
        "apc_afe_id": "4b6cebbf-ca88-4e9e-8479-dd50cc13e03d",
        "apc_op_id": {
            "name": "Navigator Corporation"
        },
        "apc_partner_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "storage_path": "afe/0.683810376905815.docx",
        "filename": "Execute Demo Outline.docx",
        "filename_display": "Execute Demo Outline",
        "mimetype": "docx",
        "byte_size": 23445,
        "checksum": null,
        "source_doc_id": null,
        "isForm": false,
        "isAttachment": false,
        "documentDate": "2026-01-26T04:39:11.663+00:00",
        "isNonOpSignedAFE": true
    }
];

export const operatorFilters = [
    {
        "id": "bbdfbc11-df12-4aec-94fd-aa97601fbdc2",
        "afe_filter": [
            {
                "Value": "No Status",
                "Column": "$STATUS",
                "Operator": "=",
                "LeftParenthesis": "("
            },
            {
                "Join": "OR",
                "Value": "Force approved by system administrator.",
                "Column": "$NOTE",
                "Operator": "CONTAINS",
                "RightParenthesis": ")"
            },
            {
                "Value": "FAPP",
                "Column": "STATUS",
                "Operator": "=",
                "LeftParenthesis": "("
            },
            {
                "Join": "OR",
                "Value": "IAPP",
                "Column": "STATUS",
                "Operator": "=",
                "RightParenthesis": ")"
            },
            {
                "Join": "AND",
                "Value": "Operated",
                "Column": "CUSTOM/OP_STATUS",
                "Operator": "="
            },
            {
                "Join": "AND",
                "Value": "100",
                "Column": "OUR_WI",
                "Operator": "<"
            }
        ],
        "well_columns": [
            "$ISPRIMARY",
            "CUSTOM/WELL_NAME_DESC",
            "$DESCRIPTION",
            "$CUSTOM/WELL_NUM"
        ]
    }
];

export const nullOperatorFilters = [
    {
        "id": "fd624e8f-8e9b-466c-9b9a-d4d47ffcc516",
        "afe_filter": null,
        "well_columns": null
    }
];

export const permissionResponseRachel = [
    {
        "apc_id": {
            "id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
            "name": "Corr and Whit Oils Company"
        },
        "address": {
            "id": 66,
            "zip": "90078",
            "city": "Houston",
            "state": "Texas",
            "suite": "",
            "active": false,
            "street": "6789 S Blvd",
            "country": "United States"
        }
    }
];

export const permissionResponseRachelNonOp = [
    {
        "apc_id": {
            "id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
            "name": "John Ross Exploration Inc"
        },
        "address": {
            "id": 10,
            "zip": "80113",
            "city": "Englewood",
            "state": "CO",
            "suite": "878",
            "active": true,
            "street": "2900 S Emerson St",
            "country": "United States"
        }
    }
];

export const genericRoleList = [
    {
        "id": 2,
        "name": "Operator View",
        "description": "Users with this privilege will have the ability to view all Operated AFEs regardless of type.",
        "title": "View Operated AFEs"
    },
    {
        "id": 3,
        "name": "Partner View",
        "description": "Users with this privilege will have the ability to view all Non-Op AFEs associated to the Non-Op address regardless of type.",
        "title": "View Non-Operated AFEs"
    },
    {
        "id": 4,
        "name": "Operator Edit Users",
        "description": "Users with this privilege will have the ability to edit users associated to Operated AFEs including adding users and deactivating users.",
        "title": "Edit Operated AFE Users"
    },
    {
        "id": 5,
        "name": "Partner Edit Users",
        "description": "Users with this privilege will have the ability to edit users associated to Non-Op AFEs including adding users and deactivating users.",
        "title": "Edit Non-Op AFE Users"
    },
    {
        "id": 6,
        "name": "Partner Edit",
        "description": "Users with this privilege will have the ability to accept or reject all Non-Op AFEs associated to a given address regardless of type.",
        "title": "Accept or Reject Non-Operated AFEs"
    },
    {
        "id": 7,
        "name": "Operator Billing",
        "description": "Users with this privilege will have the ability to view billing details from AFE Partner Connections from the Operator.  This includes seeing the number of Partners on an AFE.",
        "title": "Operator Billing Manager"
    },
    {
        "id": 8,
        "name": "Operator Library",
        "description": "Users with this privilege will be able to create, modify and delete the Partner, Partner Mappings and GL Account Code libraries associated to the Operator for Operated AFEs",
        "title": "Operated AFE Library Manager"
    },
    {
        "id": 9,
        "name": "Partner Library",
        "description": "Users with this privilege will be able to create, modify and delete the Partner and GL Account Code libraries and mappings associated to the Partner for Non-Op AFEs",
        "title": "Non-Op AFE Library Manager"
    }
];

export const userListActiveOrInactive = [
    {
        "user_id": "bffa4c85-8589-4c1f-8731-dce0e17de6b6",
        "first_name": "Easy",
        "last_name": "Test",
        "email": "easy_rider21@hotmail.com",
        "active": true
    },
    {
        "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
        "first_name": "Mike",
        "last_name": "Rider",
        "email": "mike.rider@earthlink.net",
        "active": true
    },
    {
        "user_id": "36eeb21d-9605-45e4-bcc0-ae4bda595ea9",
        "first_name": "Liam",
        "last_name": "Neilson",
        "email": "eand.v3851@gmail.com",
        "active": true
    },
    {
        "user_id": "6b02d1dc-7f5b-4482-ab68-4b3177074856",
        "first_name": "Brandon Champ",
        "last_name": "Bailey",
        "email": "brandonbailey25@gmail.com",
        "active": true
    },
    {
        "user_id": "2bdd72e2-7064-46aa-91e5-6f8ed1dc8191",
        "first_name": "Von",
        "last_name": "Miller",
        "email": "e.andv3851@gmail.com",
        "active": true
    },
    {
        "user_id": "5c76d13d-a0de-4589-9fef-f91a6817b846",
        "first_name": "Queen",
        "last_name": "Elizabeth",
        "email": "eandv3851@gmail.com",
        "active": true
    },
    {
        "user_id": "13e69340-d14c-45a9-96a8-142795925487",
        "first_name": "Rachel",
        "last_name": "Green",
        "email": "elizabeth.rider.shaw@gmail.com",
        "active": true
    },
    {
        "user_id": "11b3c839-8be8-4de2-b61b-8a0f9f56448b",
        "first_name": "Sara",
        "last_name": "Bear",
        "email": "sara.m.bibb@gmail.com",
        "active": false
    }
];

export const userPermissions = [
    {
        "role_id": 52,
        "role": 2,
        "role_active": false,
        "apc_id": "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
        "apc_name": "Navigator Corporation",
        "apc_address_id": 51,
        "street": "897 South Street",
        "suite": "",
        "city": "Dallas",
        "state": "Texas",
        "zip": "98987",
        "country": "United States",
        "user_id": "bffa4c85-8589-4c1f-8731-dce0e17de6b6",
        "first_name": "Easy",
        "last_name": "Test",
        "email": "easy_rider21@hotmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 51,
        "role": 7,
        "role_active": false,
        "apc_id": "108ab43c-c1d6-4e6d-9305-c7ac3a622cc7",
        "apc_name": "Mtn Bike Oil",
        "apc_address_id": 53,
        "street": "1234 Main Ave",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "70020",
        "country": "United States",
        "user_id": "bffa4c85-8589-4c1f-8731-dce0e17de6b6",
        "first_name": "Easy",
        "last_name": "Test",
        "email": "easy_rider21@hotmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 33,
        "role": 3,
        "role_active": false,
        "apc_id": "db863d3c-606e-4fa6-b044-812d1f3cf6eb",
        "apc_name": "Last Company",
        "apc_address_id": 7,
        "street": "6767 Main lane",
        "suite": "89",
        "city": "Denver",
        "state": "Colorado",
        "zip": "80020",
        "country": "United States",
        "user_id": "bffa4c85-8589-4c1f-8731-dce0e17de6b6",
        "first_name": "Easy",
        "last_name": "Test",
        "email": "easy_rider21@hotmail.com",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 46,
        "role": 2,
        "role_active": false,
        "apc_id": "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
        "apc_name": "Navigator Corporation",
        "apc_address_id": 51,
        "street": "897 South Street",
        "suite": "",
        "city": "Dallas",
        "state": "Texas",
        "zip": "98987",
        "country": "United States",
        "user_id": "5c76d13d-a0de-4589-9fef-f91a6817b846",
        "first_name": "Queen",
        "last_name": "Elizabeth",
        "email": "eandv3851@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 147,
        "role": 5,
        "role_active": true,
        "apc_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_name": "John Ross Exploration Inc",
        "apc_address_id": 10,
        "street": "2900 S Emerson St",
        "suite": "878",
        "city": "Englewood",
        "state": "CO",
        "zip": "80113",
        "country": "United States",
        "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
        "first_name": "Mike",
        "last_name": "Rider",
        "email": "mike.rider@earthlink.net",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 185,
        "role": 6,
        "role_active": true,
        "apc_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_name": "John Ross Exploration Inc",
        "apc_address_id": 10,
        "street": "2900 S Emerson St",
        "suite": "878",
        "city": "Englewood",
        "state": "CO",
        "zip": "80113",
        "country": "United States",
        "user_id": "13e69340-d14c-45a9-96a8-142795925487",
        "first_name": "Rachel",
        "last_name": "Green",
        "email": "elizabeth.rider.shaw@gmail.com",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 122,
        "role": 8,
        "role_active": true,
        "apc_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        "apc_name": "Corr and Whit Oils Company",
        "apc_address_id": 66,
        "street": "6789 S Blvd",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "90078",
        "country": "United States",
        "user_id": "13e69340-d14c-45a9-96a8-142795925487",
        "first_name": "Rachel",
        "last_name": "Green",
        "email": "elizabeth.rider.shaw@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 120,
        "role": 2,
        "role_active": true,
        "apc_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        "apc_name": "Corr and Whit Oils Company",
        "apc_address_id": 66,
        "street": "6789 S Blvd",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "90078",
        "country": "United States",
        "user_id": "13e69340-d14c-45a9-96a8-142795925487",
        "first_name": "Rachel",
        "last_name": "Green",
        "email": "elizabeth.rider.shaw@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 56,
        "role": 8,
        "role_active": false,
        "apc_id": "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
        "apc_name": "Navigator Corporation",
        "apc_address_id": 51,
        "street": "897 South Street",
        "suite": "",
        "city": "Dallas",
        "state": "Texas",
        "zip": "98987",
        "country": "United States",
        "user_id": "5c76d13d-a0de-4589-9fef-f91a6817b846",
        "first_name": "Queen",
        "last_name": "Elizabeth",
        "email": "eandv3851@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 50,
        "role": 7,
        "role_active": false,
        "apc_id": "108ab43c-c1d6-4e6d-9305-c7ac3a622cc7",
        "apc_name": "Mtn Bike Oil",
        "apc_address_id": 53,
        "street": "1234 Main Ave",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "70020",
        "country": "United States",
        "user_id": "5c76d13d-a0de-4589-9fef-f91a6817b846",
        "first_name": "Queen",
        "last_name": "Elizabeth",
        "email": "eandv3851@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 35,
        "role": 3,
        "role_active": true,
        "apc_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_name": "John Ross Exploration Inc",
        "apc_address_id": 10,
        "street": "2900 S Emerson St",
        "suite": "878",
        "city": "Englewood",
        "state": "CO",
        "zip": "80113",
        "country": "United States",
        "user_id": "13e69340-d14c-45a9-96a8-142795925487",
        "first_name": "Rachel",
        "last_name": "Green",
        "email": "elizabeth.rider.shaw@gmail.com",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 6,
        "role": 3,
        "role_active": false,
        "apc_id": "db863d3c-606e-4fa6-b044-812d1f3cf6eb",
        "apc_name": "Last Company",
        "apc_address_id": 7,
        "street": "6767 Main lane",
        "suite": "89",
        "city": "Denver",
        "state": "Colorado",
        "zip": "80020",
        "country": "United States",
        "user_id": "5c76d13d-a0de-4589-9fef-f91a6817b846",
        "first_name": "Queen",
        "last_name": "Elizabeth",
        "email": "eandv3851@gmail.com",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 186,
        "role": 3,
        "role_active": false,
        "apc_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        "apc_name": "Athena Minerals Inc.",
        "apc_address_id": 7,
        "street": "6767 Main lane",
        "suite": "89",
        "city": "Denver",
        "state": "Colorado",
        "zip": "80020",
        "country": "United States",
        "user_id": "13e69340-d14c-45a9-96a8-142795925487",
        "first_name": "Rachel",
        "last_name": "Green",
        "email": "elizabeth.rider.shaw@gmail.com",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 9,
        "role": 9,
        "role_active": false,
        "apc_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        "apc_name": "Athena Minerals Inc.",
        "apc_address_id": 7,
        "street": "6767 Main lane",
        "suite": "89",
        "city": "Denver",
        "state": "Colorado",
        "zip": "80020",
        "country": "United States",
        "user_id": "5c76d13d-a0de-4589-9fef-f91a6817b846",
        "first_name": "Queen",
        "last_name": "Elizabeth",
        "email": "eandv3851@gmail.com",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 237,
        "role": 2,
        "role_active": true,
        "apc_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        "apc_name": "Corr and Whit Oils Company",
        "apc_address_id": 66,
        "street": "6789 S Blvd",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "90078",
        "country": "United States",
        "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
        "first_name": "Mike",
        "last_name": "Rider",
        "email": "mike.rider@earthlink.net",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 238,
        "role": 4,
        "role_active": true,
        "apc_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        "apc_name": "Corr and Whit Oils Company",
        "apc_address_id": 66,
        "street": "6789 S Blvd",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "90078",
        "country": "United States",
        "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
        "first_name": "Mike",
        "last_name": "Rider",
        "email": "mike.rider@earthlink.net",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 74,
        "role": 5,
        "role_active": true,
        "apc_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_name": "John Ross Exploration Inc",
        "apc_address_id": 10,
        "street": "2900 S Emerson St",
        "suite": "878",
        "city": "Englewood",
        "state": "CO",
        "zip": "80113",
        "country": "United States",
        "user_id": "13e69340-d14c-45a9-96a8-142795925487",
        "first_name": "Rachel",
        "last_name": "Green",
        "email": "elizabeth.rider.shaw@gmail.com",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 57,
        "role": 8,
        "role_active": false,
        "apc_id": "108ab43c-c1d6-4e6d-9305-c7ac3a622cc7",
        "apc_name": "Mtn Bike Oil",
        "apc_address_id": 53,
        "street": "1234 Main Ave",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "70020",
        "country": "United States",
        "user_id": "5c76d13d-a0de-4589-9fef-f91a6817b846",
        "first_name": "Queen",
        "last_name": "Elizabeth",
        "email": "eandv3851@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 40,
        "role": 4,
        "role_active": false,
        "apc_id": "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
        "apc_name": "Navigator Corporation",
        "apc_address_id": 51,
        "street": "897 South Street",
        "suite": "",
        "city": "Dallas",
        "state": "Texas",
        "zip": "98987",
        "country": "United States",
        "user_id": "bffa4c85-8589-4c1f-8731-dce0e17de6b6",
        "first_name": "Easy",
        "last_name": "Test",
        "email": "easy_rider21@hotmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 148,
        "role": 9,
        "role_active": true,
        "apc_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_name": "John Ross Exploration Inc",
        "apc_address_id": 10,
        "street": "2900 S Emerson St",
        "suite": "878",
        "city": "Englewood",
        "state": "CO",
        "zip": "80113",
        "country": "United States",
        "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
        "first_name": "Mike",
        "last_name": "Rider",
        "email": "mike.rider@earthlink.net",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 127,
        "role": null,
        "role_active": true,
        "apc_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        "apc_name": "Corr and Whit Oils Company",
        "apc_address_id": 66,
        "street": "6789 S Blvd",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "90078",
        "country": "United States",
        "user_id": "2bdd72e2-7064-46aa-91e5-6f8ed1dc8191",
        "first_name": "Von",
        "last_name": "Miller",
        "email": "e.andv3851@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 72,
        "role": 9,
        "role_active": true,
        "apc_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_name": "John Ross Exploration Inc",
        "apc_address_id": 10,
        "street": "2900 S Emerson St",
        "suite": "878",
        "city": "Englewood",
        "state": "CO",
        "zip": "80113",
        "country": "United States",
        "user_id": "13e69340-d14c-45a9-96a8-142795925487",
        "first_name": "Rachel",
        "last_name": "Green",
        "email": "elizabeth.rider.shaw@gmail.com",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 7,
        "role": 9,
        "role_active": false,
        "apc_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        "apc_name": "Athena Minerals Inc.",
        "apc_address_id": 7,
        "street": "6767 Main lane",
        "suite": "89",
        "city": "Denver",
        "state": "Colorado",
        "zip": "80020",
        "country": "United States",
        "user_id": "bffa4c85-8589-4c1f-8731-dce0e17de6b6",
        "first_name": "Easy",
        "last_name": "Test",
        "email": "easy_rider21@hotmail.com",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 41,
        "role": 2,
        "role_active": false,
        "apc_id": "108ab43c-c1d6-4e6d-9305-c7ac3a622cc7",
        "apc_name": "Mtn Bike Oil",
        "apc_address_id": 53,
        "street": "1234 Main Ave",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "70020",
        "country": "United States",
        "user_id": "5c76d13d-a0de-4589-9fef-f91a6817b846",
        "first_name": "Queen",
        "last_name": "Elizabeth",
        "email": "eandv3851@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 49,
        "role": 7,
        "role_active": false,
        "apc_id": "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
        "apc_name": "Navigator Corporation",
        "apc_address_id": 51,
        "street": "897 South Street",
        "suite": "",
        "city": "Dallas",
        "state": "Texas",
        "zip": "98987",
        "country": "United States",
        "user_id": "5c76d13d-a0de-4589-9fef-f91a6817b846",
        "first_name": "Queen",
        "last_name": "Elizabeth",
        "email": "eandv3851@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 128,
        "role": 2,
        "role_active": true,
        "apc_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        "apc_name": "Corr and Whit Oils Company",
        "apc_address_id": 66,
        "street": "6789 S Blvd",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "90078",
        "country": "United States",
        "user_id": "2bdd72e2-7064-46aa-91e5-6f8ed1dc8191",
        "first_name": "Von",
        "last_name": "Miller",
        "email": "e.andv3851@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 239,
        "role": 8,
        "role_active": true,
        "apc_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        "apc_name": "Corr and Whit Oils Company",
        "apc_address_id": 66,
        "street": "6789 S Blvd",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "90078",
        "country": "United States",
        "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
        "first_name": "Mike",
        "last_name": "Rider",
        "email": "mike.rider@earthlink.net",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 197,
        "role": 9,
        "role_active": true,
        "apc_id": "ecb2c585-9225-4957-98ce-d4315af4e47b",
        "apc_name": "Corr and Whit Oils Company",
        "apc_address_id": 48,
        "street": "1875 Lawrence St",
        "suite": null,
        "city": "Denver",
        "state": "CO",
        "zip": "80202",
        "country": "United States",
        "user_id": "13e69340-d14c-45a9-96a8-142795925487",
        "first_name": "Rachel",
        "last_name": "Green",
        "email": "elizabeth.rider.shaw@gmail.com",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 34,
        "role": 3,
        "role_active": false,
        "apc_id": "db863d3c-606e-4fa6-b044-812d1f3cf6eb",
        "apc_name": "Last Company",
        "apc_address_id": 7,
        "street": "6767 Main lane",
        "suite": "89",
        "city": "Denver",
        "state": "Colorado",
        "zip": "80020",
        "country": "United States",
        "user_id": "bffa4c85-8589-4c1f-8731-dce0e17de6b6",
        "first_name": "Easy",
        "last_name": "Test",
        "email": "easy_rider21@hotmail.com",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 124,
        "role": 2,
        "role_active": false,
        "apc_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        "apc_name": "Corr and Whit Oils Company",
        "apc_address_id": 66,
        "street": "6789 S Blvd",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "90078",
        "country": "United States",
        "user_id": "5c76d13d-a0de-4589-9fef-f91a6817b846",
        "first_name": "Queen",
        "last_name": "Elizabeth",
        "email": "eandv3851@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 32,
        "role": 6,
        "role_active": true,
        "apc_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        "apc_name": "Athena Minerals Inc.",
        "apc_address_id": 7,
        "street": "6767 Main lane",
        "suite": "89",
        "city": "Denver",
        "state": "Colorado",
        "zip": "80020",
        "country": "United States",
        "user_id": "bffa4c85-8589-4c1f-8731-dce0e17de6b6",
        "first_name": "Easy",
        "last_name": "Test",
        "email": "easy_rider21@hotmail.com",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 146,
        "role": 3,
        "role_active": true,
        "apc_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_name": "John Ross Exploration Inc",
        "apc_address_id": 10,
        "street": "2900 S Emerson St",
        "suite": "878",
        "city": "Englewood",
        "state": "CO",
        "zip": "80113",
        "country": "United States",
        "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
        "first_name": "Mike",
        "last_name": "Rider",
        "email": "mike.rider@earthlink.net",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 290,
        "role": 2,
        "role_active": true,
        "apc_id": "108ab43c-c1d6-4e6d-9305-c7ac3a622cc7",
        "apc_name": "Mtn Bike Oil",
        "apc_address_id": 53,
        "street": "1234 Main Ave",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "70020",
        "country": "United States",
        "user_id": "2bdd72e2-7064-46aa-91e5-6f8ed1dc8191",
        "first_name": "Von",
        "last_name": "Miller",
        "email": "e.andv3851@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 35,
        "role": 4,
        "role_active": false,
        "apc_id": "a4367e56-14bf-4bd1-b0f1-fecc7d97b58c",
        "apc_name": "Navigator Corporation",
        "apc_address_id": 51,
        "street": "897 South Street",
        "suite": "",
        "city": "Dallas",
        "state": "Texas",
        "zip": "98987",
        "country": "United States",
        "user_id": "5c76d13d-a0de-4589-9fef-f91a6817b846",
        "first_name": "Queen",
        "last_name": "Elizabeth",
        "email": "eandv3851@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 121,
        "role": 4,
        "role_active": true,
        "apc_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        "apc_name": "Corr and Whit Oils Company",
        "apc_address_id": 66,
        "street": "6789 S Blvd",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "90078",
        "country": "United States",
        "user_id": "13e69340-d14c-45a9-96a8-142795925487",
        "first_name": "Rachel",
        "last_name": "Green",
        "email": "elizabeth.rider.shaw@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 39,
        "role": 4,
        "role_active": false,
        "apc_id": "108ab43c-c1d6-4e6d-9305-c7ac3a622cc7",
        "apc_name": "Mtn Bike Oil",
        "apc_address_id": 53,
        "street": "1234 Main Ave",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "70020",
        "country": "United States",
        "user_id": "5c76d13d-a0de-4589-9fef-f91a6817b846",
        "first_name": "Queen",
        "last_name": "Elizabeth",
        "email": "eandv3851@gmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 198,
        "role": 9,
        "role_active": true,
        "apc_id": "ecb2c585-9225-4957-98ce-d4315af4e47b",
        "apc_name": "Corr and Whit Oils Company",
        "apc_address_id": 48,
        "street": "1875 Lawrence St",
        "suite": null,
        "city": "Denver",
        "state": "CO",
        "zip": "80202",
        "country": "United States",
        "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
        "first_name": "Mike",
        "last_name": "Rider",
        "email": "mike.rider@earthlink.net",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 2,
        "role": 3,
        "role_active": true,
        "apc_id": "626390b5-6f63-4caa-a0aa-b333a15eaf59",
        "apc_name": "Athena Minerals Inc.",
        "apc_address_id": 7,
        "street": "6767 Main lane",
        "suite": "89",
        "city": "Denver",
        "state": "Colorado",
        "zip": "80020",
        "country": "United States",
        "user_id": "bffa4c85-8589-4c1f-8731-dce0e17de6b6",
        "first_name": "Easy",
        "last_name": "Test",
        "email": "easy_rider21@hotmail.com",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 125,
        "role": 2,
        "role_active": true,
        "apc_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        "apc_name": "Corr and Whit Oils Company",
        "apc_address_id": 66,
        "street": "6789 S Blvd",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "90078",
        "country": "United States",
        "user_id": "bffa4c85-8589-4c1f-8731-dce0e17de6b6",
        "first_name": "Easy",
        "last_name": "Test",
        "email": "easy_rider21@hotmail.com",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    }
];

export const limitedPermissionList = [
    {
        "role_id": 237,
        "role": 2,
        "role_active": true,
        "apc_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        "apc_name": "Corr and Whit Oils Company",
        "apc_address_id": 66,
        "street": "6789 S Blvd",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "90078",
        "country": "United States",
        "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
        "first_name": "Mike",
        "last_name": "Rider",
        "email": "mike.rider@earthlink.net",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 237,
        "role": 4,
        "role_active": false,
        "apc_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
        "apc_name": "Corr and Whit Oils Company",
        "apc_address_id": 66,
        "street": "6789 S Blvd",
        "suite": "",
        "city": "Houston",
        "state": "Texas",
        "zip": "90078",
        "country": "United States",
        "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
        "first_name": "Mike",
        "last_name": "Rider",
        "email": "mike.rider@earthlink.net",
        "user_active": true,
        "is_op_permission": true,
        "is_partner_permission": false
    },
    {
        "role_id": 146,
        "role": 3,
        "role_active": true,
        "apc_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_name": "John Ross Exploration Inc",
        "apc_address_id": 10,
        "street": "2900 S Emerson St",
        "suite": "878",
        "city": "Englewood",
        "state": "CO",
        "zip": "80113",
        "country": "United States",
        "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
        "first_name": "Mike",
        "last_name": "Rider",
        "email": "mike.rider@earthlink.net",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
    {
        "role_id": 146,
        "role": 5,
        "role_active": false,
        "apc_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
        "apc_name": "John Ross Exploration Inc",
        "apc_address_id": 10,
        "street": "2900 S Emerson St",
        "suite": "878",
        "city": "Englewood",
        "state": "CO",
        "zip": "80113",
        "country": "United States",
        "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
        "first_name": "Mike",
        "last_name": "Rider",
        "email": "mike.rider@earthlink.net",
        "user_active": true,
        "is_op_permission": false,
        "is_partner_permission": true
    },
];

export const updatedPermissions = [
    {
       "active": false,
       "apc_address_id": 66,
       "apc_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
       "id": 237,
       "role": 2,
       "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
     },
     {
       "active": true,
       "apc_address_id": 66,
       "apc_id": "3b34a78a-13ad-40b5-aecd-268d56dd5e0d",
       "id": 237,
       "role": 4,
       "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
   },
];

export const updatedNonPermissions = [
    {
       "active": false,
       "apc_address_id": 10,
       "apc_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
       "id": 146,
       "role": 3,
       "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
     },
     {
       "active": true,
       "apc_address_id": 10,
       "apc_id": "8ed0a285-0011-4f56-962f-c46bc0889d1b",
       "id": NaN,
       "role": 9,
       "user_id": "77ef7dd6-bd03-4500-b599-ad1447e8c489",
   },
]